"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.$ontologyRid = exports.$osdkMetadata = exports.$Queries = exports.twoDimensionalAggregationFunction = exports.threeDimensionalAggregationFunction = exports.returnsTimestamp = exports.returnsObject = exports.returnsDate = exports.incrementPersonAge = exports.addOne = exports.$Objects = exports.Office = exports.ObjectWithTimestampPrimaryKey = exports.objectTypeWithAllPropertyTypes = exports.equipment = exports.Employee = exports.$Interfaces = exports.FooInterface = exports.$Actions = exports.moveOffice = exports.createOfficeAndEmployee = exports.createOffice = exports.actionTakesObjectSet = void 0;
var actions_js_1 = require("./ontology/actions.js");
Object.defineProperty(exports, "actionTakesObjectSet", { enumerable: true, get: function () { return actions_js_1.actionTakesObjectSet; } });
Object.defineProperty(exports, "createOffice", { enumerable: true, get: function () { return actions_js_1.createOffice; } });
Object.defineProperty(exports, "createOfficeAndEmployee", { enumerable: true, get: function () { return actions_js_1.createOfficeAndEmployee; } });
Object.defineProperty(exports, "moveOffice", { enumerable: true, get: function () { return actions_js_1.moveOffice; } });
exports.$Actions = require("./ontology/actions.js");
var interfaces_js_1 = require("./ontology/interfaces.js");
Object.defineProperty(exports, "FooInterface", { enumerable: true, get: function () { return interfaces_js_1.FooInterface; } });
exports.$Interfaces = require("./ontology/interfaces.js");
var objects_js_1 = require("./ontology/objects.js");
Object.defineProperty(exports, "Employee", { enumerable: true, get: function () { return objects_js_1.Employee; } });
Object.defineProperty(exports, "equipment", { enumerable: true, get: function () { return objects_js_1.equipment; } });
Object.defineProperty(exports, "objectTypeWithAllPropertyTypes", { enumerable: true, get: function () { return objects_js_1.objectTypeWithAllPropertyTypes; } });
Object.defineProperty(exports, "ObjectWithTimestampPrimaryKey", { enumerable: true, get: function () { return objects_js_1.ObjectWithTimestampPrimaryKey; } });
Object.defineProperty(exports, "Office", { enumerable: true, get: function () { return objects_js_1.Office; } });
exports.$Objects = require("./ontology/objects.js");
var queries_js_1 = require("./ontology/queries.js");
Object.defineProperty(exports, "addOne", { enumerable: true, get: function () { return queries_js_1.addOne; } });
Object.defineProperty(exports, "incrementPersonAge", { enumerable: true, get: function () { return queries_js_1.incrementPersonAge; } });
Object.defineProperty(exports, "returnsDate", { enumerable: true, get: function () { return queries_js_1.returnsDate; } });
Object.defineProperty(exports, "returnsObject", { enumerable: true, get: function () { return queries_js_1.returnsObject; } });
Object.defineProperty(exports, "returnsTimestamp", { enumerable: true, get: function () { return queries_js_1.returnsTimestamp; } });
Object.defineProperty(exports, "threeDimensionalAggregationFunction", { enumerable: true, get: function () { return queries_js_1.threeDimensionalAggregationFunction; } });
Object.defineProperty(exports, "twoDimensionalAggregationFunction", { enumerable: true, get: function () { return queries_js_1.twoDimensionalAggregationFunction; } });
exports.$Queries = require("./ontology/queries.js");
var OntologyMetadata_js_1 = require("./OntologyMetadata.js");
Object.defineProperty(exports, "$osdkMetadata", { enumerable: true, get: function () { return OntologyMetadata_js_1.$osdkMetadata; } });
var OntologyMetadata_js_2 = require("./OntologyMetadata.js");
Object.defineProperty(exports, "$ontologyRid", { enumerable: true, get: function () { return OntologyMetadata_js_2.$ontologyRid; } });
