version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
