/*
 * Copyright 2025 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { readFile } from "node:fs/promises";
import * as path from "node:path";

import { findUp } from "find-up";
import { defineConfig, type UserConfig } from "tsdown";

const packageJson = JSON.parse(await readFile("package.json", "utf-8"));

// Compile-time constants inlined via define. TS is handled natively by
// rolldown/oxc, so no babel step is needed. dts is generated by typecheck.sh
// (which renames the CJS `.d.ts` to `.d.cts`), so it is disabled here.
const baseConfig: UserConfig = {
  entry: ["src/index.ts", "src/public/*.ts", "src/public/*.mts"],
  outExtensions: () => ({ js: ".js" }),
  env: {
    PACKAGE_VERSION: packageJson.version,
    PACKAGE_API_VERSION: await readPackageVersion("packages/api"),
    PACKAGE_CLIENT_VERSION: await readPackageVersion("packages/client"),
    PACKAGE_CLI_VERSION: await readPackageVersion("packages/cli"),
    TARGET: "node",
    MODE: process.env.production ? "production" : "development",
  },
  clean: false, // we do this ourselves so its granular
  logLevel: "silent",
  dts: false,
  sourcemap: true,
  shims: true, // so we can use __dirname in both esm and cjs
  minify: "dce-only",
  treeshake: true,
  target: "es2022",
};

const esmConfig: UserConfig = {
  ...baseConfig,
  format: ["esm"],
  platform: "node",
  outDir: "build/esm",
};

const cjsConfig: UserConfig = {
  ...baseConfig,
  format: ["cjs"],
  platform: "node",
  outExtensions: () => ({ js: ".cjs" }),
  outDir: "build/cjs",
};

const browserConfig: UserConfig = {
  ...baseConfig,
  format: ["esm"],
  platform: "browser",
  outDir: "build/browser",
  env: {
    ...baseConfig.env,
    TARGET: "browser",
  },
};

export default defineConfig([esmConfig, browserConfig, cjsConfig]);

async function readPackageVersion(k: string): Promise<string> {
  const workspaceFile = await findUp("pnpm-workspace.yaml");
  if (!workspaceFile) throw new Error("couldn't find workspace file");
  const workspaceRoot = path.dirname(workspaceFile);
  return readFile(path.join(workspaceRoot, k, "package.json"), "utf-8").then(
    (f) => JSON.parse(f).version
  );
}
