packages:
  - "packages/*"
  - "examples/*"
  - "examples-extra/*"
  - "examples-extra/basic/*"
  - "tests/*"
  - "benchmarks/*/*"

catalog:
  "@osdk/docs-spec-core": ^0.5.0
  "@osdk/docs-spec-sdk": ^0.14.0
  "@osdk/foundry": 2.41.0
  "@osdk/foundry.core": 2.41.0
  "@osdk/foundry.datasets": ~2.5.0
  "@osdk/foundry.geo": 2.41.0
  "@osdk/foundry.mediasets": 2.41.0
  "@osdk/foundry.ontologies": 2.41.0
  "@osdk/foundry.thirdpartyapplications": 2.41.0
  "@osdk/internal.foundry.ontologies": 2.41.0
