/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { getTokenRole, TOKEN_ROLES } from "./token-map.js";
import type { ExtractedColor, TokenAssignment } from "./types.js";

interface ResolvedToken {
  role: string;
  label: string;
  value: string;
  cssProperties: string[];
}

function resolveTokens(
  palette: ExtractedColor[],
  assignments: TokenAssignment[],
): ResolvedToken[] {
  const resolved: ResolvedToken[] = [];

  for (const assignment of assignments) {
    const roleDef = getTokenRole(assignment.role);
    if (!roleDef) continue;

    let value: string | undefined;
    if (assignment.colorIndex >= 0 && palette[assignment.colorIndex]) {
      value = palette[assignment.colorIndex].hex;
    } else if (assignment.customValue) {
      value = assignment.customValue;
    }

    if (!value) continue;

    // Append unit suffix for px/ms inputs if the value is purely numeric
    if (
      (roleDef.inputType === "px" || roleDef.inputType === "ms")
      && /^\d+(\.\d+)?$/.test(value)
    ) {
      value = `${value}${roleDef.inputType}`;
    }

    resolved.push({
      role: assignment.role,
      label: roleDef.label,
      value,
      cssProperties: roleDef.cssProperties,
    });
  }

  return resolved;
}

/** Generate CSS custom properties wrapped in @layer user.theme */
export function generateCss(
  palette: ExtractedColor[],
  assignments: TokenAssignment[],
): string {
  const tokens = resolveTokens(palette, assignments);
  if (tokens.length === 0) return "/* No tokens configured */\n";

  const lines: string[] = [
    "/* Brand Theme — Generated by OSDK Brand Theme Extractor */",
    "@layer user.theme {",
    "  :root {",
  ];

  // Group by category for readability
  const categories = ["color", "typography", "surface", "emphasis"] as const;

  for (const category of categories) {
    const categoryTokens = tokens.filter((t) => {
      const def = TOKEN_ROLES.find((r) => r.role === t.role);
      return def?.category === category;
    });

    if (categoryTokens.length === 0) continue;

    lines.push("");
    lines.push(
      `    /* ${category.charAt(0).toUpperCase() + category.slice(1)} */`,
    );

    for (const token of categoryTokens) {
      lines.push(`    /* ${token.label} — ${token.value} */`);
      for (const prop of token.cssProperties) {
        lines.push(`    ${prop}: ${token.value};`);
      }
    }
  }

  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/** Generate a Markdown documentation table */
export function generateMarkdown(
  palette: ExtractedColor[],
  assignments: TokenAssignment[],
): string {
  const tokens = resolveTokens(palette, assignments);
  if (tokens.length === 0) return "No tokens configured.\n";

  const lines: string[] = [
    "# Brand Theme Tokens",
    "",
    "*Generated by OSDK Brand Theme Extractor*",
    "",
  ];

  // Palette section
  if (palette.length > 0) {
    lines.push("## Extracted Palette");
    lines.push("");
    lines.push("| Swatch | Hex | Luminance | Chroma |");
    lines.push("|--------|-----|-----------|--------|");
    for (const color of palette) {
      lines.push(
        `| ![${color.hex}](https://via.placeholder.com/20/${
          color.hex.slice(1)
        }/${color.hex.slice(1)}) | \`${color.hex}\` | ${
          (color.luminance * 100).toFixed(1)
        }% | ${color.chroma.toFixed(3)} |`,
      );
    }
    lines.push("");
  }

  // Token assignments
  lines.push("## Token Assignments");
  lines.push("");
  lines.push("| Role | Value | CSS Properties |");
  lines.push("|------|-------|----------------|");

  for (const token of tokens) {
    const props = token.cssProperties.map((p) => `\`${p}\``).join(", ");
    lines.push(`| ${token.label} | \`${token.value}\` | ${props} |`);
  }

  lines.push("");
  return lines.join("\n");
}
