/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { getTokenRole } from "./token-map.js";
import type { TokenAssignment } from "./types.js";

interface ResolvedToken {
  role: string;
  label: string;
  value: string;
  category: string;
  cssProperties: string[];
}

function resolveTokens(
  assignments: TokenAssignment[],
): ResolvedToken[] {
  const resolved: ResolvedToken[] = [];

  for (const assignment of assignments) {
    const roleDef = getTokenRole(assignment.role);
    if (!roleDef) continue;

    let value: string | undefined = assignment.customValue;

    if (!value) continue;

    // Append unit suffix for px/ms inputs if the value is purely numeric
    if (
      (roleDef.inputType === "px" || roleDef.inputType === "ms")
      && /^\d+(\.\d+)?$/.test(value)
    ) {
      value = `${value}${roleDef.inputType}`;
    }

    resolved.push({
      role: assignment.role,
      label: roleDef.label,
      value,
      category: roleDef.category,
      cssProperties: roleDef.cssProperties,
    });
  }

  return resolved;
}

/** Generate CSS custom properties wrapped in @layer user.theme */
export function generateCss(
  assignments: TokenAssignment[],
): string {
  const tokens = resolveTokens(assignments);
  if (tokens.length === 0) return "/* No tokens configured */\n";

  const lines: string[] = [
    "/* Brand Theme — Generated by OSDK Brand Theme Extractor */",
    "@layer user.theme {",
    "  :root {",
  ];

  const categories = ["color", "typography", "surface", "emphasis"] as const;

  for (const category of categories) {
    const categoryTokens = tokens.filter((t) => t.category === category);

    if (categoryTokens.length === 0) continue;

    lines.push("");
    lines.push(
      `    /* ${category.charAt(0).toUpperCase() + category.slice(1)} */`,
    );

    for (const token of categoryTokens) {
      lines.push(`    /* ${token.label} — ${token.value} */`);
      for (const prop of token.cssProperties) {
        lines.push(`    ${prop}: ${token.value};`);
      }
    }
  }

  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

// ── Color role descriptions ─────────────────────────────

const COLOR_ROLE_DESCRIPTIONS: Record<string, string> = {
  background:
    "Page canvas and default surface — the base layer of the visual hierarchy.",
  surface:
    "Elevated panels, cards, table headers, and hover states — sits above background.",
  text: "Primary body text — used for all default-weight readable content.",
  "text-muted":
    "Secondary text for labels, captions, and helper content — reduced contrast.",
  primary:
    "Brand accent — CTAs, focus rings, active indicators, links, and checkboxes.",
  "primary-foreground":
    "Text rendered on primary-colored surfaces — must meet WCAG AA against primary.",
  secondary: "Secondary button backgrounds and subtle interactive surfaces.",
  "secondary-foreground":
    "Text on secondary surfaces and default intent foreground.",
  "icon-color": "Muted iconography and drag handles.",
  border:
    "Surface borders, table dividers, input outlines, and checkbox borders.",
  danger: "Destructive actions, validation errors, and error states.",
  success: "Success confirmations, positive feedback, and completion states.",
  warning:
    "Warning states, caution indicators, and attention-required signals.",
};

/**
 * Generate a DESIGN.md file following the awesome-design-md format.
 * Includes YAML front matter with structured tokens and prose sections
 * describing the design language.
 *
 * @see https://github.com/nicholasgriffintn/awesome-design-md
 */
export function generateMarkdown(
  assignments: TokenAssignment[],
): string {
  const tokens = resolveTokens(assignments);
  if (tokens.length === 0) return "No tokens configured.\n";

  const colorTokens = tokens.filter((t) => t.category === "color");
  const typographyTokens = tokens.filter((t) => t.category === "typography");
  const surfaceTokens = tokens.filter((t) => t.category === "surface");
  const emphasisTokens = tokens.filter((t) => t.category === "emphasis");

  const get = (role: string): string | undefined =>
    tokens.find((t) => t.role === role)?.value;

  const bg = get("background");
  const primary = get("primary");
  const text = get("text");
  const fontFamily = get("font-family");
  const borderRadius = get("border-radius");
  const spacing = get("spacing");
  const borderWidth = get("border-width");
  const shadow = get("shadow");
  const isDark = isLikelyDarkTheme(bg);

  const lines: string[] = [];

  // ── YAML Front Matter ─────────────────────────────────
  lines.push("---");
  lines.push("version: alpha");
  lines.push("name: brand-theme");
  lines.push(`description: >-`);
  lines.push(`  ${buildDescription(bg, primary, text, fontFamily, isDark)}`);
  lines.push("");

  // Colors
  if (colorTokens.length > 0) {
    lines.push("colors:");
    for (const token of colorTokens) {
      lines.push(`  ${token.role}: "${token.value}"`);
    }
    lines.push("");
  }

  // Typography
  if (typographyTokens.length > 0) {
    const fontWeightDefault = get("font-weight-default") ?? "400";
    const fontWeightBold = get("font-weight-bold") ?? "600";
    const lineHeight = get("line-height") ?? "1.5";
    const sizeSmall = get("font-size-small");
    const sizeMedium = get("font-size-medium");
    const sizeLarge = get("font-size-large");

    lines.push("typography:");

    if (fontWeightBold && sizeLarge) {
      writeTypographyEntry(lines, "heading", {
        fontFamily,
        fontSize: sizeLarge,
        fontWeight: fontWeightBold,
        lineHeight: "1.2",
      });
    }
    if (sizeLarge) {
      writeTypographyEntry(lines, "body-lg", {
        fontFamily,
        fontSize: sizeLarge,
        fontWeight: fontWeightDefault,
        lineHeight,
      });
    }
    if (sizeMedium) {
      writeTypographyEntry(lines, "body-md", {
        fontFamily,
        fontSize: sizeMedium,
        fontWeight: fontWeightDefault,
        lineHeight,
      });
    }
    if (sizeSmall) {
      writeTypographyEntry(lines, "body-sm", {
        fontFamily,
        fontSize: sizeSmall,
        fontWeight: fontWeightDefault,
        lineHeight,
      });
    }
    lines.push("");
  }

  // Rounded scale
  if (borderRadius) {
    const base = parseNumeric(borderRadius);
    lines.push("rounded:");
    if (base != null) {
      lines.push(`  xs: ${Math.max(1, Math.round(base * 0.5))}px`);
      lines.push(`  sm: ${base}px`);
      lines.push(`  md: ${Math.round(base * 2)}px`);
      lines.push(`  lg: ${Math.round(base * 3)}px`);
      lines.push(`  xl: ${Math.round(base * 4)}px`);
      lines.push("  pill: 9999px");
    } else {
      lines.push(`  default: ${borderRadius}`);
    }
    lines.push("");
  }

  // Spacing scale
  if (spacing) {
    const base = parseNumeric(spacing);
    lines.push("spacing:");
    if (base != null) {
      lines.push(`  xs: ${Math.round(base * 0.5)}px`);
      lines.push(`  sm: ${base}px`);
      lines.push(`  md: ${Math.round(base * 2)}px`);
      lines.push(`  lg: ${Math.round(base * 3)}px`);
      lines.push(`  xl: ${Math.round(base * 4)}px`);
      lines.push(`  xxl: ${Math.round(base * 6)}px`);
    } else {
      lines.push(`  default: ${spacing}`);
    }
    lines.push("");
  }

  // Elevation
  if (shadow) {
    lines.push("elevation:");
    lines.push("  0: flat");
    lines.push(`  1: "${shadow}"`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // ── Prose Sections ────────────────────────────────────

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(
    buildOverview(bg, primary, text, fontFamily, borderRadius, isDark),
  );
  lines.push("");

  // Colors
  if (colorTokens.length > 0) {
    lines.push("## Colors");
    lines.push("");

    // Group colors by semantic purpose
    const brandColors = colorTokens.filter(
      (t) =>
        [
          "background",
          "surface",
          "primary",
          "primary-foreground",
          "secondary",
          "secondary-foreground",
        ].includes(
          t.role,
        ),
    );
    const textColors = colorTokens.filter(
      (t) => ["text", "text-muted", "icon-color"].includes(t.role),
    );
    const borderColors = colorTokens.filter(
      (t) => t.role === "border",
    );
    const semanticColors = colorTokens.filter(
      (t) => ["danger", "success", "warning"].includes(t.role),
    );

    if (brandColors.length > 0) {
      lines.push("### Brand & Surface");
      for (const token of brandColors) {
        const desc = COLOR_ROLE_DESCRIPTIONS[token.role] ?? "";
        lines.push(
          `- **${token.label}** (\`${token.value}\`): ${desc}`,
        );
      }
      lines.push("");
    }

    if (textColors.length > 0) {
      lines.push("### Text & Iconography");
      for (const token of textColors) {
        const desc = COLOR_ROLE_DESCRIPTIONS[token.role] ?? "";
        lines.push(
          `- **${token.label}** (\`${token.value}\`): ${desc}`,
        );
      }
      lines.push("");
    }

    if (borderColors.length > 0) {
      lines.push("### Borders");
      for (const token of borderColors) {
        const desc = COLOR_ROLE_DESCRIPTIONS[token.role] ?? "";
        lines.push(
          `- **${token.label}** (\`${token.value}\`): ${desc}`,
        );
      }
      lines.push("");
    }

    if (semanticColors.length > 0) {
      lines.push("### Semantic");
      for (const token of semanticColors) {
        const desc = COLOR_ROLE_DESCRIPTIONS[token.role] ?? "";
        lines.push(
          `- **${token.label}** (\`${token.value}\`): ${desc}`,
        );
      }
      lines.push("");
    }
  }

  // Typography
  if (typographyTokens.length > 0) {
    lines.push("## Typography");
    lines.push("");
    if (fontFamily) {
      const primaryFont = fontFamily.split(",")[0].trim().replace(/['"]/g, "");
      lines.push(`### Font Family`);
      lines.push("");
      lines.push(
        `The theme uses **${primaryFont}** as the primary typeface. The full stack is \`${fontFamily}\`, ensuring consistent rendering across platforms with graceful degradation to system fonts.`,
      );
      lines.push("");
    }

    lines.push("### Hierarchy");
    lines.push("");
    lines.push("| Token | Size | Weight | Line Height | Use |");
    lines.push("|-------|------|--------|-------------|-----|");
    const sizeSmall = get("font-size-small");
    const sizeMedium = get("font-size-medium");
    const sizeLarge = get("font-size-large");
    const weightDefault = get("font-weight-default") ?? "400";
    const weightBold = get("font-weight-bold") ?? "600";
    const lh = get("line-height") ?? "1.5";

    if (weightBold && sizeLarge) {
      lines.push(
        `| heading | ${sizeLarge} | ${weightBold} | 1.2 | Section headings, card titles |`,
      );
    }
    if (sizeLarge) {
      lines.push(
        `| body-lg | ${sizeLarge} | ${weightDefault} | ${lh} | Lead paragraphs, emphasized body |`,
      );
    }
    if (sizeMedium) {
      lines.push(
        `| body-md | ${sizeMedium} | ${weightDefault} | ${lh} | Default body text |`,
      );
    }
    if (sizeSmall) {
      lines.push(
        `| body-sm | ${sizeSmall} | ${weightDefault} | ${lh} | Captions, metadata, helper text |`,
      );
    }
    lines.push("");
  }

  // Layout & Surface
  if (surfaceTokens.length > 0 || emphasisTokens.length > 0) {
    lines.push("## Layout & Surface");
    lines.push("");

    if (borderRadius) {
      const base = parseNumeric(borderRadius);
      lines.push("### Border Radius");
      lines.push("");
      if (base != null) {
        lines.push("| Token | Value | Use |");
        lines.push("|-------|-------|-----|");
        lines.push(
          `| xs | ${
            Math.max(1, Math.round(base * 0.5))
          }px | Tags, small badges |`,
        );
        lines.push(`| sm | ${base}px | Inputs, small cards |`);
        lines.push(`| md | ${Math.round(base * 2)}px | Cards, panels |`);
        lines.push(`| lg | ${Math.round(base * 3)}px | Modals, large cards |`);
        lines.push(
          `| xl | ${Math.round(base * 4)}px | Hero sections, feature cards |`,
        );
        lines.push("| pill | 9999px | Buttons, tag pills |");
        lines.push("");
      } else {
        lines.push(`Default border radius: \`${borderRadius}\`.`);
        lines.push("");
      }
    }

    if (spacing) {
      lines.push("### Spacing");
      lines.push("");
      const base = parseNumeric(spacing);
      if (base != null) {
        lines.push(
          `Base spacing unit is **${base}px**. Scale: xs (${
            Math.round(base * 0.5)
          }px), sm (${base}px), md (${Math.round(base * 2)}px), lg (${
            Math.round(base * 3)
          }px), xl (${Math.round(base * 4)}px), xxl (${
            Math.round(base * 6)
          }px).`,
        );
      } else {
        lines.push(`Base spacing: \`${spacing}\`.`);
      }
      lines.push("");
    }

    if (borderWidth) {
      lines.push(`### Borders`);
      lines.push("");
      lines.push(`Default border width: \`${borderWidth}\`.`);
      lines.push("");
    }

    if (shadow) {
      lines.push("### Elevation");
      lines.push("");
      lines.push("| Level | Treatment | Use |");
      lines.push("|-------|-----------|-----|");
      lines.push("| 0 | Flat | Default surface |");
      lines.push(
        `| 1 | \`${shadow}\` | Cards, dropdowns, floating panels |`,
      );
      lines.push("");
    }
  }

  // Emphasis & Motion
  if (emphasisTokens.length > 0) {
    lines.push("## Emphasis & Motion");
    lines.push("");
    const focusWidth = get("focus-width");
    const focusOffset = get("focus-offset");
    const transition = get("transition-duration");

    if (focusWidth || focusOffset) {
      lines.push(
        `Focus indicators use a **${focusWidth ?? "2px"}** outline with **${
          focusOffset ?? "2px"
        }** offset, colored to match the primary accent. This ensures keyboard navigation is visible without disrupting the layout.`,
      );
      lines.push("");
    }
    if (transition) {
      lines.push(
        `Transitions use a **${transition}** duration for interactive state changes (hover, focus, active). This provides responsive feedback without feeling sluggish or jarring.`,
      );
      lines.push("");
    }
  }

  // Do's and Don'ts
  lines.push("## Do's and Don'ts");
  lines.push("");
  lines.push("### Do");
  if (primary) {
    lines.push(
      `- Reserve \`${primary}\` for filled CTAs and interactive emphasis — it should appear sparingly, as the single chromatic accent.`,
    );
  }
  lines.push(
    "- Maintain WCAG AA contrast ratios: 4.5:1 for body text, 3:1 for large text and UI components.",
  );
  lines.push(
    "- Use the CSS custom properties (`--osdk-*`, `--bp-*`) rather than hardcoding values — the cascade ensures components stay consistent.",
  );
  if (borderRadius) {
    lines.push(
      `- Apply the radius scale consistently — \`sm\` for inputs, \`md\` for cards, \`pill\` for buttons.`,
    );
  }
  if (isDark) {
    lines.push(
      "- Test all states (hover, focus, disabled) on dark surfaces — contrast failures are harder to spot on dark backgrounds.",
    );
  }
  lines.push("");
  lines.push("### Don't");
  lines.push(
    "- Don't override component-level tokens directly — set the semantic role tokens and let the cascade propagate.",
  );
  lines.push(
    "- Don't mix brand colors with Blueprint palette primitives (`--bp-palette-*`) — they feed into oklch derivation chains that will produce unexpected results.",
  );
  if (primary) {
    lines.push(
      `- Don't use \`${primary}\` as body text color — it's an accent, not a reading color.`,
    );
  }
  if (isDark) {
    lines.push(
      "- Don't assume light-mode contrast ratios hold on dark surfaces — re-validate after switching color modes.",
    );
  }
  lines.push("");

  // Iteration Guide
  lines.push("## Iteration Guide");
  lines.push("");
  lines.push("1. Focus on ONE component at a time.");
  lines.push(
    "2. Reference token roles by name (`background`, `primary`, `text`) rather than raw hex values.",
  );
  lines.push(
    "3. Use the `@layer user.theme` CSS export to apply tokens — the layer ensures correct cascade priority.",
  );
  lines.push(
    "4. Test contrast ratios after every color change — the Brand Theme panel shows live WCAG badges.",
  );
  lines.push(
    "5. Export updated CSS and DESIGN.md after changes to keep documentation in sync.",
  );
  lines.push("");

  return lines.join("\n");
}

// ── Helpers ─────────────────────────────────────────────

function writeTypographyEntry(
  lines: string[],
  name: string,
  props: {
    fontFamily: string | undefined;
    fontSize: string;
    fontWeight: string;
    lineHeight: string;
  },
): void {
  lines.push(`  ${name}:`);
  if (props.fontFamily) lines.push(`    fontFamily: "${props.fontFamily}"`);
  lines.push(`    fontSize: ${props.fontSize}`);
  lines.push(`    fontWeight: ${props.fontWeight}`);
  lines.push(`    lineHeight: ${props.lineHeight}`);
}

function parseNumeric(value: string): number | undefined {
  const match = /^(\d+(?:\.\d+)?)/.exec(value);
  return match ? parseFloat(match[1]) : undefined;
}

function isLikelyDarkTheme(bg: string | undefined): boolean {
  if (!bg) return false;
  const hex = bg.replace("#", "");
  if (hex.length !== 6) return false;
  const r = parseInt(hex.slice(0, 2), 16);
  const g = parseInt(hex.slice(2, 4), 16);
  const b = parseInt(hex.slice(4, 6), 16);
  // Rough luminance check
  return (r * 0.299 + g * 0.587 + b * 0.114) < 80;
}

function buildDescription(
  bg: string | undefined,
  primary: string | undefined,
  text: string | undefined,
  fontFamily: string | undefined,
  isDark: boolean,
): string {
  const parts: string[] = [];

  if (isDark) {
    parts.push(
      `A dark-mode theme${bg ? ` built on a \`${bg}\` canvas` : ""}`,
    );
  } else {
    parts.push(
      `A light-mode theme${bg ? ` built on a \`${bg}\` canvas` : ""}`,
    );
  }

  if (primary) {
    parts.push(`with \`${primary}\` as the primary accent`);
  }

  if (text) {
    parts.push(`and \`${text}\` for body text`);
  }

  if (fontFamily) {
    const primaryFont = fontFamily.split(",")[0].trim().replace(/['"]/g, "");
    parts.push(`using ${primaryFont} typography`);
  }

  return parts.join(", ")
    + ". Defines semantic color, typography, surface, and emphasis tokens for OSDK components.";
}

function buildOverview(
  bg: string | undefined,
  primary: string | undefined,
  text: string | undefined,
  fontFamily: string | undefined,
  borderRadius: string | undefined,
  isDark: boolean,
): string {
  const parts: string[] = [];

  if (isDark) {
    parts.push(
      `This is a **dark-mode** theme${
        bg ? ` anchored on \`${bg}\`— a deep, near-black canvas` : ""
      } that prioritizes contrast and readability in low-light environments.`,
    );
  } else {
    parts.push(
      `This is a **light-mode** theme${
        bg ? ` built on a \`${bg}\` canvas` : ""
      } designed for clarity and comfortable extended reading.`,
    );
  }

  if (primary) {
    parts.push(
      `The primary accent \`${primary}\` is used sparingly for CTAs, focus indicators, and interactive emphasis — never as a decorative fill.`,
    );
  }

  if (text) {
    parts.push(
      `Body text is set in \`${text}\`${
        isDark
          ? ", chosen for comfortable contrast against the dark canvas without being pure white"
          : ""
      }.`,
    );
  }

  if (fontFamily) {
    const primaryFont = fontFamily.split(",")[0].trim().replace(/['"]/g, "");
    parts.push(
      `Typography uses **${primaryFont}** with system-font fallbacks for consistent cross-platform rendering.`,
    );
  }

  if (borderRadius) {
    const base = parseNumeric(borderRadius);
    if (base != null) {
      if (base <= 2) {
        parts.push(
          "Shapes use sharp corners for a precise, technical aesthetic.",
        );
      } else if (base <= 4) {
        parts.push(
          `Shapes use a \`${base}px\` base radius — subtle enough to soften edges without losing a professional feel.`,
        );
      } else if (base <= 8) {
        parts.push(
          `Shapes use a \`${base}px\` base radius for a friendly, approachable character.`,
        );
      } else {
        parts.push(
          `Shapes use a generous \`${base}px\` base radius for a soft, rounded character.`,
        );
      }
    }
  }

  return parts.join(" ");
}
