/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { getTokenRole, TOKEN_ROLES } from "./token-map.js";
import type { TokenAssignment } from "./types.js";

interface ResolvedToken {
  role: string;
  label: string;
  value: string;
  cssProperties: string[];
}

function resolveTokens(assignments: TokenAssignment[]): ResolvedToken[] {
  const resolved: ResolvedToken[] = [];

  for (const assignment of assignments) {
    const roleDef = getTokenRole(assignment.role);
    if (!roleDef) continue;

    let value: string | undefined = assignment.customValue;

    if (!value) continue;

    // Append unit suffix for px/ms inputs if the value is purely numeric
    if (
      (roleDef.inputType === "px" || roleDef.inputType === "ms") &&
      /^\d+(\.\d+)?$/.test(value)
    ) {
      value = `${value}${roleDef.inputType}`;
    }

    resolved.push({
      role: assignment.role,
      label: roleDef.label,
      value,
      cssProperties: roleDef.cssProperties,
    });
  }

  return resolved;
}

/** Generate CSS custom properties wrapped in @layer user.theme */
export function generateCss(assignments: TokenAssignment[]): string {
  const tokens = resolveTokens(assignments);
  if (tokens.length === 0) return "/* No tokens configured */\n";

  const lines: string[] = [
    "/* Brand Theme — Generated by OSDK Brand Theme Extractor */",
    "@layer user.theme {",
    "  :root {",
  ];

  // Group by category for readability
  const categories = ["color", "typography", "surface", "emphasis"] as const;

  for (const category of categories) {
    const categoryTokens = tokens.filter((t) => {
      const def = TOKEN_ROLES.find((r) => r.role === t.role);
      return def?.category === category;
    });

    if (categoryTokens.length === 0) continue;

    lines.push("");
    lines.push(
      `    /* ${category.charAt(0).toUpperCase() + category.slice(1)} */`
    );

    for (const token of categoryTokens) {
      lines.push(`    /* ${token.label} — ${token.value} */`);
      for (const prop of token.cssProperties) {
        lines.push(`    ${prop}: ${token.value};`);
      }
    }
  }

  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/** Generate a DESIGN.md with YAML frontmatter and token reference table */
export function generateMarkdown(assignments: TokenAssignment[]): string {
  const tokens = resolveTokens(assignments);
  if (tokens.length === 0) return "No tokens configured.\n";

  // Group tokens by their DESIGN.md section
  const sections = new Map<string, { key: string; value: string }[]>();
  for (const token of tokens) {
    const def = TOKEN_ROLES.find((r) => r.role === token.role);
    if (!def) continue;
    const section = def.designMdSection;
    let entries = sections.get(section);
    if (!entries) {
      entries = [];
      sections.set(section, entries);
    }
    entries.push({ key: def.designMdKey, value: token.value });
  }

  const lines: string[] = ["---"];
  lines.push("version: alpha");
  lines.push("name: OSDK-brand-theme");
  lines.push(
    'description: "Brand theme generated by OSDK Brand Theme Extractor"'
  );

  // Emit each section in a stable order
  const sectionOrder = [
    "colors",
    "typography",
    "rounded",
    "spacing",
    "surface",
    "emphasis",
  ];

  for (const sectionName of sectionOrder) {
    const entries = sections.get(sectionName);
    if (!entries || entries.length === 0) continue;

    lines.push("");
    lines.push(`${sectionName}:`);

    if (sectionName === "typography") {
      // Typography tokens are grouped into a single "body" composite
      lines.push("  body:");
      for (const entry of entries) {
        lines.push(`    ${entry.key}: ${quoteIfNeeded(entry.value)}`);
      }
    } else {
      for (const entry of entries) {
        lines.push(`  ${entry.key}: ${quoteIfNeeded(entry.value)}`);
      }
    }
  }

  lines.push("---");
  lines.push("");

  // Append a reference table with CSS property mappings
  lines.push("## Token Reference");
  lines.push("");
  lines.push("*Generated by OSDK Brand Theme Extractor*");
  lines.push("");
  lines.push("| Token | Value | CSS Properties |");
  lines.push("|-------|-------|----------------|");

  for (const token of tokens) {
    const def = TOKEN_ROLES.find((r) => r.role === token.role);
    const tokenPath = def
      ? `{${def.designMdSection}.${def.designMdKey}}`
      : token.role;
    const props = token.cssProperties.map((p) => `\`${p}\``).join(", ");
    lines.push(`| \`${tokenPath}\` | \`${token.value}\` | ${props} |`);
  }

  lines.push("");
  return lines.join("\n");
}

function quoteIfNeeded(value: string): string {
  // Quote hex colors and values with spaces/special chars
  if (value.startsWith("#") || /\s/.test(value) || value.includes(",")) {
    return `"${value}"`;
  }
  return value;
}
