#!/usr/bin/env node
/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable no-console */

import { promises as fs } from "fs";
import { createRequire } from "module";
import path from "path";
import postcss from "postcss";
import postcssModules from "postcss-modules";
import * as sass from "sass-embedded";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const srcDir = path.join(packageRoot, "src");
const buildDir = path.join(packageRoot, "build", "esm");
const styleElementId = "__osdk_react_devtools_styles__";

const requireFromHere = createRequire(import.meta.url);

async function findFilesByExt(dir, ext) {
  const entries = await fs.readdir(dir, {
    recursive: true,
    withFileTypes: true,
  });
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(ext))
    .map((e) => path.join(e.parentPath, e.name));
}

async function compileScssModule(scssPath) {
  const compileResult = sass.compile(scssPath, {
    style: "expanded",
    sourceMap: false,
    loadPaths: [path.dirname(scssPath)],
  });

  let exportedClasses = {};
  const postcssResult = await postcss([
    postcssModules({
      generateScopedName: "[name]__[local]___[hash:base64:8]",
      getJSON(_cssFileName, json) {
        exportedClasses = json;
      },
    }),
  ]).process(compileResult.css, { from: scssPath });

  return {
    css: postcssResult.css,
    classes: exportedClasses,
  };
}

function readPackageCss(specifier) {
  let resolved;
  try {
    resolved = requireFromHere.resolve(specifier);
  } catch (e) {
    throw new Error(
      `build-css: cannot resolve "${specifier}". `
        + `Did you run \`pnpm install\`?`,
      { cause: e },
    );
  }
  return fs.readFile(resolved, "utf8");
}

function buildRuntimeInjectionSource(css) {
  return `/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// AUTO-GENERATED by scripts/build-css.mjs. Do not edit by hand.

const css = ${JSON.stringify(css)};

if (
  typeof document !== "undefined"
  && !document.getElementById(${JSON.stringify(styleElementId)})
) {
  const style = document.createElement("style");
  style.id = ${JSON.stringify(styleElementId)};
  style.textContent = css;
  document.head.appendChild(style);
}

export {};
`;
}

async function rewriteScssImports() {
  const jsFiles = await findFilesByExt(buildDir, ".js");
  // Matches every form esbuild/babel can emit: `from "..."`, `import("...")`,
  // and bare side-effect `import "...";`.
  const re =
    /(from\s+["']|import\s*\(\s*["']|import\s+["'])([^"']+\.module\.scss)(["'])/g;
  for (const jsFile of jsFiles) {
    const original = await fs.readFile(jsFile, "utf8");
    const updated = original.replace(re, "$1$2.js$3");
    if (updated !== original) {
      await fs.writeFile(jsFile, updated, "utf8");
    }
  }
}

async function cleanStaleScssProxies(currentScssSrcPaths) {
  const expectedProxyPaths = new Set(
    currentScssSrcPaths.map((scssPath) =>
      path.join(buildDir, path.relative(srcDir, scssPath) + ".js")
    ),
  );
  const allJsFiles = await findFilesByExt(buildDir, ".module.scss.js");
  for (const jsFile of allJsFiles) {
    if (!expectedProxyPaths.has(jsFile)) {
      await fs.rm(jsFile, { force: true });
    }
  }
}

async function writeProxyFile(scssSrcPath, classes) {
  const relFromSrc = path.relative(srcDir, scssSrcPath);
  const proxyPath = path.join(buildDir, relFromSrc + ".js");
  const content =
    `// AUTO-GENERATED by scripts/build-css.mjs. Do not edit by hand.
const styles = ${JSON.stringify(classes, null, 2)};
export default styles;
`;
  await fs.mkdir(path.dirname(proxyPath), { recursive: true });
  await fs.writeFile(proxyPath, content, "utf8");
}

async function main() {
  const scssFiles = await findFilesByExt(srcDir, ".module.scss");

  await cleanStaleScssProxies(scssFiles);

  let combinedModuleCss = "";
  for (const scssFile of scssFiles) {
    const { css, classes } = await compileScssModule(scssFile);
    await writeProxyFile(scssFile, classes);
    const relativeLabel = path.relative(srcDir, scssFile);
    combinedModuleCss += `/* ${relativeLabel} */\n${css}\n`;
  }

  const blueprintCoreCss = await readPackageCss(
    "@blueprintjs/core/lib/css/blueprint.css",
  );
  const blueprintIconsCss = await readPackageCss(
    "@blueprintjs/icons/lib/css/blueprint-icons.css",
  );

  const combinedCss = [
    "/* @osdk/react-devtools - Combined styles */",
    "/* @blueprintjs/core */",
    blueprintCoreCss,
    "/* @blueprintjs/icons */",
    blueprintIconsCss,
    combinedModuleCss,
  ].join("\n\n");

  await fs.mkdir(buildDir, { recursive: true });
  await fs.writeFile(path.join(buildDir, "styles.css"), combinedCss, "utf8");
  await fs.writeFile(
    path.join(buildDir, "styles.js"),
    buildRuntimeInjectionSource(combinedCss),
    "utf8",
  );

  await rewriteScssImports();

  console.log(
    `build-css: wrote styles.css (${combinedCss.length} chars), `
      + `styles.js, and ${scssFiles.length} SCSS-module proxies`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
