/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// cspell:disable
// Every identifier below is a language or script code defined by the platform, not prose. Disabling
// for the whole file keeps a platform bump that adds an exotic language name from failing
// check-spelling and needing a new dictionary entry.

// Mirrors the closed enums declared by the platform in `@osdk/foundry.mediasets`
// (`OcrLanguage`, `OcrScript`, `TranscriptionLanguage`). They are copied rather than re-exported
// because `@osdk/api` does not depend on any `@osdk/foundry.*` package; see the note in
// `actions/ActionResults.ts`. The `AssertPlatformParity` aliases at the bottom of
// `makeMediaTransformation.ts` in `@osdk/client` keep these equal to the generated unions, and are
// what fails when a platform bump changes a value.

/**
 * A language for OCR (Optical Character Recognition) operations.
 *
 * @experimental
 */
export type OcrLanguage =
  | "AFR"
  | "AMH"
  | "ARA"
  | "ASM"
  | "AZE"
  | "AZE_CYRL"
  | "BEL"
  | "BEN"
  | "BOD"
  | "BOS"
  | "BRE"
  | "BUL"
  | "CAT"
  | "CEB"
  | "CES"
  | "CHI_SIM"
  | "CHI_SIM_VERT"
  | "CHI_TRA"
  | "CHI_TRA_VERT"
  | "CHR"
  | "COS"
  | "CYM"
  | "DAN"
  | "DEU"
  | "DIV"
  | "DZO"
  | "ELL"
  | "ENG"
  | "ENM"
  | "EPO"
  | "EST"
  | "EUS"
  | "FAO"
  | "FAS"
  | "FIL"
  | "FIN"
  | "FRA"
  | "FRM"
  | "FRY"
  | "GLA"
  | "GLE"
  | "GLG"
  | "GRC"
  | "GUJ"
  | "HAT"
  | "HEB"
  | "HIN"
  | "HRV"
  | "HUN"
  | "HYE"
  | "IKU"
  | "IND"
  | "ISL"
  | "ITA"
  | "ITA_OLD"
  | "JAV"
  | "JPN"
  | "JPN_VERT"
  | "KAN"
  | "KAT"
  | "KAT_OLD"
  | "KAZ"
  | "KHM"
  | "KIR"
  | "KMR"
  | "KOR"
  | "KOR_VERT"
  | "LAO"
  | "LAT"
  | "LAV"
  | "LIT"
  | "LTZ"
  | "MAL"
  | "MAR"
  | "MKD"
  | "MLT"
  | "MON"
  | "MRI"
  | "MSA"
  | "MYA"
  | "NEP"
  | "NLD"
  | "NOR"
  | "OCI"
  | "ORI"
  | "OSD"
  | "PAN"
  | "POL"
  | "POR"
  | "PUS"
  | "QUE"
  | "RON"
  | "RUS"
  | "SAN"
  | "SIN"
  | "SLK"
  | "SLV"
  | "SND"
  | "SPA"
  | "SPA_OLD"
  | "SQI"
  | "SRP"
  | "SRP_LATN"
  | "SUN"
  | "SWA"
  | "SWE"
  | "SYR"
  | "TAM"
  | "TAT"
  | "TEL"
  | "TGK"
  | "THA"
  | "TIR"
  | "TON"
  | "TUR"
  | "UIG"
  | "UKR"
  | "URD"
  | "UZB"
  | "UZB_CYRL"
  | "VIE"
  | "YID"
  | "YOR";

/**
 * A script for OCR (Optical Character Recognition) operations.
 *
 * @experimental
 */
export type OcrScript =
  | "ARABIC"
  | "ARMENIAN"
  | "BENGALI"
  | "CANADIAN_ABORIGINAL"
  | "CHEROKEE"
  | "CYRILLIC"
  | "DEVANAGARI"
  | "ETHIOPIC"
  | "FRAKTUR"
  | "GEORGIAN"
  | "GREEK"
  | "GUJARATI"
  | "GURMUKHI"
  | "HAN_SIMPLIFIED"
  | "HAN_SIMPLIFIED_VERT"
  | "HAN_TRADITIONAL"
  | "HAN_TRADITIONAL_VERT"
  | "HANGUL"
  | "HANGUL_VERT"
  | "HEBREW"
  | "JAPANESE"
  | "JAPANESE_VERT"
  | "KANNADA"
  | "KHMER"
  | "LAO"
  | "LATIN"
  | "MALAYALAM"
  | "MYANMAR"
  | "ORIYA"
  | "SINHALA"
  | "SYRIAC"
  | "TAMIL"
  | "TELUGU"
  | "THAANA"
  | "THAI"
  | "TIBETAN"
  | "VIETNAMESE";

/**
 * A language for audio transcription operations.
 *
 * Note the `"false"` member. The platform spec lists the ISO code for Norwegian as an unquoted `NO`
 * in `media-item-transformations.yml`, which YAML coerces to a boolean, so every SDK generated from
 * that spec emits `"false"` in place of `"NO"`. This union reproduces the generated one exactly, so
 * the anomaly is copied deliberately rather than corrected here: `"NO"` is not currently a value the
 * platform declares, and quoting it in the spec is the fix that repairs every SDK at once.
 *
 * @experimental
 */
export type TranscriptionLanguage =
  | "AF"
  | "AM"
  | "AR"
  | "AS"
  | "AZ"
  | "BA"
  | "BE"
  | "BG"
  | "BN"
  | "BO"
  | "BR"
  | "BS"
  | "CA"
  | "CS"
  | "CY"
  | "DA"
  | "DE"
  | "EL"
  | "EN"
  | "ES"
  | "ET"
  | "EU"
  | "FA"
  | "FI"
  | "FO"
  | "FR"
  | "GL"
  | "GU"
  | "HA"
  | "HAW"
  | "HE"
  | "HI"
  | "HR"
  | "HT"
  | "HU"
  | "HY"
  | "ID"
  | "IS"
  | "IT"
  | "JA"
  | "JW"
  | "KA"
  | "KK"
  | "KM"
  | "KN"
  | "KO"
  | "LA"
  | "LB"
  | "LN"
  | "LO"
  | "LT"
  | "LV"
  | "MG"
  | "MI"
  | "MK"
  | "ML"
  | "MN"
  | "MR"
  | "MS"
  | "MT"
  | "MY"
  | "NE"
  | "NL"
  | "NN"
  | "false"
  | "OC"
  | "PA"
  | "PL"
  | "PS"
  | "PT"
  | "RO"
  | "RU"
  | "SA"
  | "SD"
  | "SI"
  | "SK"
  | "SL"
  | "SN"
  | "SO"
  | "SQ"
  | "SR"
  | "SU"
  | "SV"
  | "SW"
  | "TA"
  | "TE"
  | "TG"
  | "TH"
  | "TK"
  | "TL"
  | "TR"
  | "TT"
  | "UK"
  | "UR"
  | "UZ"
  | "VI"
  | "YI"
  | "YO"
  | "YUE"
  | "ZH"
  | "AFRIKAANS"
  | "ALBANIAN"
  | "AMHARIC"
  | "ARABIC"
  | "ARMENIAN"
  | "ASSAMESE"
  | "AZERBAIJANI"
  | "BASHKIR"
  | "BASQUE"
  | "BELARUSIAN"
  | "BENGALI"
  | "BOSNIAN"
  | "BRETON"
  | "BULGARIAN"
  | "BURMESE"
  | "CANTONESE"
  | "CASTILIAN"
  | "CATALAN"
  | "CHINESE"
  | "CROATIAN"
  | "CZECH"
  | "DANISH"
  | "DUTCH"
  | "ENGLISH"
  | "ESTONIAN"
  | "FAROESE"
  | "FINNISH"
  | "FLEMISH"
  | "FRENCH"
  | "GALICIAN"
  | "GEORGIAN"
  | "GERMAN"
  | "GREEK"
  | "GUJARATI"
  | "HAITIAN"
  | "HAITIAN_CREOLE"
  | "HAUSA"
  | "HAWAIIAN"
  | "HEBREW"
  | "HINDI"
  | "HUNGARIAN"
  | "ICELANDIC"
  | "INDONESIAN"
  | "ITALIAN"
  | "JAPANESE"
  | "JAVANESE"
  | "KANNADA"
  | "KAZAKH"
  | "KHMER"
  | "KOREAN"
  | "LAO"
  | "LATIN"
  | "LATVIAN"
  | "LETZEBURGESCH"
  | "LINGALA"
  | "LITHUANIAN"
  | "LUXEMBOURGISH"
  | "MACEDONIAN"
  | "MALAGASY"
  | "MALAY"
  | "MALAYALAM"
  | "MALTESE"
  | "MANDARIN"
  | "MAORI"
  | "MARATHI"
  | "MOLDAVIAN"
  | "MOLDOVAN"
  | "MONGOLIAN"
  | "MYANMAR"
  | "NEPALI"
  | "NORWEGIAN"
  | "NYNORSK"
  | "OCCITAN"
  | "PANJABI"
  | "PASHTO"
  | "PERSIAN"
  | "POLISH"
  | "PORTUGUESE"
  | "PUNJABI"
  | "PUSHTO"
  | "ROMANIAN"
  | "RUSSIAN"
  | "SANSKRIT"
  | "SERBIAN"
  | "SHONA"
  | "SINDHI"
  | "SINHALA"
  | "SINHALESE"
  | "SLOVAK"
  | "SLOVENIAN"
  | "SOMALI"
  | "SPANISH"
  | "SUNDANESE"
  | "SWAHILI"
  | "SWEDISH"
  | "TAGALOG"
  | "TAJIK"
  | "TAMIL"
  | "TATAR"
  | "TELUGU"
  | "THAI"
  | "TIBETAN"
  | "TURKISH"
  | "TURKMEN"
  | "UKRAINIAN"
  | "URDU"
  | "UZBEK"
  | "VALENCIAN"
  | "VIETNAMESE"
  | "WELSH"
  | "YIDDISH"
  | "YORUBA";
