/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { ParameterId } from "@osdk/client.unstable";
import type {
  ActionLevelValidationDefinition,
  ActionParameterConfiguration,
  ActionSection,
  ActionStatus,
  ActionType,
  BlueprintIcon,
  DefaultFormat,
  MappingValue,
  SubmissionMetadata,
  TableConfiguration,
} from "@osdk/maker";
import { defineAction, kebab } from "@osdk/maker";

export type FunctionBackedActionTypeUserDefinition = {
  functionApiName: string;
  apiName?: string;
  displayName?: string;
  status?: ActionStatus;
  parameterConfiguration?: Record<string, ActionParameterConfiguration>;
  nonParameterMappings?: Record<string, MappingValue>;
  actionLevelValidation?: ActionLevelValidationDefinition;
  excludedProperties?: Array<ParameterId>;
  sections?: Array<ActionSection>;
  defaultFormat?: DefaultFormat;
  enableLayoutSwitch?: boolean;
  tableConfiguration?: TableConfiguration;
  parameterOrdering?: Array<string>;
  submissionMetadata?: SubmissionMetadata;
  // Used for Create or Modify actions
  primaryKeyOption?: "autoGenerated" | "userInput";
  icon?: { locator: BlueprintIcon; color: string };
};

export function defineFunctionBackedAction(
  def: FunctionBackedActionTypeUserDefinition,
): ActionType {
  const actionApiName = def.apiName
    ?? `function-action-${kebab(def.functionApiName)}`;
  return defineAction({
    apiName: def.apiName ?? def.functionApiName.toLowerCase(),
    displayName: def.displayName ?? `Function action ${def.functionApiName}`,
    rules: [{
      type: "functionRule",
      functionRule: {
        // delegate this to conversion step
        functionRid: def.functionApiName,
        functionInputValues: {},
        functionVersion: "0.1.0",
      },
    }],
    status: def.status ?? "active",
    ...({
      validation: [{
        condition: {
          type: "true",
          true: {},
        },
        displayMetadata: {
          failureMessage: "Validation failed",
          typeClasses: [],
        },
      }],
    }),
  });
}
