"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Office = exports.ObjectWithTimestampPrimaryKey = exports.objectTypeWithAllPropertyTypes = exports.equipment = exports.Employee = void 0;
var Employee_js_1 = require("./objects/Employee.js");
Object.defineProperty(exports, "Employee", { enumerable: true, get: function () { return Employee_js_1.Employee; } });
var equipment_js_1 = require("./objects/equipment.js");
Object.defineProperty(exports, "equipment", { enumerable: true, get: function () { return equipment_js_1.equipment; } });
var objectTypeWithAllPropertyTypes_js_1 = require("./objects/objectTypeWithAllPropertyTypes.js");
Object.defineProperty(exports, "objectTypeWithAllPropertyTypes", { enumerable: true, get: function () { return objectTypeWithAllPropertyTypes_js_1.objectTypeWithAllPropertyTypes; } });
var ObjectWithTimestampPrimaryKey_js_1 = require("./objects/ObjectWithTimestampPrimaryKey.js");
Object.defineProperty(exports, "ObjectWithTimestampPrimaryKey", { enumerable: true, get: function () { return ObjectWithTimestampPrimaryKey_js_1.ObjectWithTimestampPrimaryKey; } });
var Office_js_1 = require("./objects/Office.js");
Object.defineProperty(exports, "Office", { enumerable: true, get: function () { return Office_js_1.Office; } });
