/*
 * Copyright 2025 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { DocsSnippetsSpec } from "../spec.js";

export const OSDK_SNIPPETS_SPEC = {
  "version": 1,
  "snippets": {
    "loadSingleObjectGuide": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadObjectPageGuide": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "orderObjectsGuide": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "searchObjectsGuide": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadSingleObjectReference": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadObjectsReference": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadAllObjectsReference": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadLinkedObjectReference": {
      "variables": {
        "sourceObjectType": "required",
        "linkedObjectType": "required",
        "linkApiName": "required",
        "linkApiNameSnakeCase": "required",
        "isLinkManySided": "required",
        "linkedProperties": "required",
        "linkedPrimaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadLinkedObjectsReference": {
      "variables": {
        "sourceObjectType": "required",
        "linkedObjectType": "required",
        "linkApiName": "required",
        "linkApiNameSnakeCase": "required",
        "isLinkManySided": "required",
        "linkedProperties": "required",
        "linkedPrimaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "aggregationTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "countAggregationTemplate": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "approximateDistinctAggregationTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "exactDistinctAggregationTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "numericAggregationTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "operation": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "fixedWidthGroupByTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "durationGroupByTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "duration": "required",
        "durationText": "required",
        "durationLowercase": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "exactGroupByTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "rangeGroupByTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "operation": "required",
        "operationSymbol": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "applyAction": {
      "variables": {
        "hasAttachmentUpload": "required",
        "attachmentProperty": "optional",
        "hasAttachmentImports": "required",
        "actionApiName": "required",
        "rawActionApiName": "required",
        "actionApiNameUpperCaseFirstCharacter": "required",
        "actionApiNameSnakeCase": "required",
        "hasTimestampInputs": "required",
        "hasDateInputs": "required",
        "needsImports": "required",
        "actionEditAddObjectTypes": "required",
        "actionEditModifyObjectTypes": "required",
        "actionEditDeleteObjectCount": "required",
        "actionEditAddedLinksCount": "required",
        "actionEditDeletedLinksCount": "required",
        "hasEditObjectTypes": "required",
        "hasParameters": "required",
        "actionTypeParameterValues": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "batchApplyAction": {
      "variables": {
        "hasAttachmentUpload": "required",
        "attachmentProperty": "optional",
        "hasAttachmentImports": "required",
        "actionApiName": "required",
        "rawActionApiName": "required",
        "actionApiNameUpperCaseFirstCharacter": "required",
        "actionApiNameSnakeCase": "required",
        "hasTimestampInputs": "required",
        "hasDateInputs": "required",
        "needsImports": "required",
        "actionEditAddObjectTypes": "required",
        "actionEditModifyObjectTypes": "required",
        "actionEditDeleteObjectCount": "required",
        "actionEditAddedLinksCount": "required",
        "actionEditDeletedLinksCount": "required",
        "hasEditObjectTypes": "required",
        "hasParameters": "required",
        "actionTypeParameterValues": "required",
        "actionApiNameBatchRequest": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "uploadAttachment": {
      "variables": {
        "packageName": "required",
      },
    },
    "uploadMedia": {
      "variables": {
        "objectType": "required",
        "rawObjectTypeApiName": "required",
        "property": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "readMedia": {
      "variables": {
        "objectType": "required",
        "rawObjectTypeApiName": "required",
        "property": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "castInterfaceToObjectReference": {
      "variables": {
        "interfaceApiName": "required",
        "objectTypeApiName": "required",
        "interfaceApiNameCamelCase": "required",
        "objectTypeApiNameCamelCase": "required",
        "packageName": "required",
      },
    },
    "executeFunction": {
      "variables": {
        "hasAttachmentUpload": "required",
        "attachmentProperty": "optional",
        "hasAttachmentImports": "required",
        "funcApiName": "required",
        "rawFuncApiName": "required",
        "funcApiNameSnakeCase": "required",
        "functionInputValues": "required",
        "hasTimestampInputs": "required",
        "hasDateInputs": "required",
        "needsImports": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "stringStartsWithTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "containsAllTermsInOrderTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "containsAnyTermTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "containsAllTermsTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "equalityTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "inFilterTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "nullTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "rangeTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "withinDistanceTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "distanceUnit": "required",
        "distanceUnitText": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "withinBoundingBoxTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "withinPolygonTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "intersectsPolygonTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "intersects": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "intersectsBboxTemplate": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "intersects": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "notTemplate": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "andTemplate": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "orTemplate": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadInterfacesReference": {
      "variables": {
        "interfaceApiName": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadAllInterfacesReference": {
      "variables": {
        "interfaceApiName": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadOrderedInterfacesReference": {
      "variables": {
        "interfaceApiName": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "searchInterfacesReference": {
      "variables": {
        "interfaceApiName": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadTimeSeriesPointsSnippet": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadRelativeTimeSeriesPointsSnippet": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "timeUnit": "required",
        "timeUnitValue": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadAbsoluteTimeSeriesPointsSnippet": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadTimeSeriesFirstPointSnippet": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadTimeSeriesLastPointSnippet": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "loadObjectMetadataSnippet": {
      "variables": {
        "objectType": "required",
        "property": "required",
        "propertySnakeCase": "required",
        "isDateProperty": "required",
        "isTimestampProperty": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "propertyValue": "required",
        "rawPropertyValue": "required",
        "propertyValueIncremented": "required",
        "rawPropertyValueIncremented": "required",
        "rawOntologyApiName": "required",
        "packageName": "required",
      },
    },
    "subscribeToObjectSetInstructions": {
      "variables": {
        "objectType": "required",
        "titleProperty": "required",
        "titlePropertySnakeCase": "required",
        "allCapsTitlePropertySnakeCase": "required",
        "properties": "required",
        "primaryKeyProperty": "required",
        "packageName": "required",
      },
    },
  },
} as const;

// Can't add "as const satisfies DocsSnippetsSpec" above as it causes:
// Variable must have an explicit type annotation with --isolatedDeclarations.ts(9010)
// So instead, type check it here:
export const __validSpec: DocsSnippetsSpec = OSDK_SNIPPETS_SPEC;
