export {
  actionTakesAllParameterTypes,
  assignEmployee1,
  createFooInterface,
  createMediaObject,
  createMediaViaFunction,
  createOsdkTestObject,
  createStructPerson,
  createStructPersonOpiTeam,
  createTestGeoAction,
  createTodo,
  createUnstructuredImageExample,
  deleteFooInterface,
  deleteOsdkTestObject,
  editOsdkTestObject,
} from './ontology/actions.js';
export * as $Actions from './ontology/actions.js';
export {
  Athlete,
  bus_1,
  CollateralConcernCandidate,
  CollateralConcernList,
  EsongInterfaceA,
  FooInterface,
  TestAsTypeIltInterface,
  InterfaceNoProps,
  mwaltherPerson,
  NihalbCastingInterfaceB,
  NihalbCastingInterfaceTypeA,
  NihalbCastingLinkedInterfaceTypeA,
  OsdkTestInterface,
} from './ontology/interfaces.js';
export * as $Interfaces from './ontology/interfaces.js';
export {
  BgaoNflPlayer,
  BoundariesUsState,
  BuilderDeploymentState,
  Country_1,
  DherlihyComplexObject,
  Employee,
  EsongIssues,
  EsongPds,
  FintrafficAis,
  GraphqlFormatting,
  GtfsTripTrackObject,
  MasonHeavyEquipment,
  MasonMovie,
  MatthewvsDevOrderEmbedding,
  McAirportStruct,
  MnayanOsdkMediaObject,
  MtaBus,
  NbaPlayer,
  NihalbCastingLinkedObjectTypeA,
  NihalbCastingObjectTypeA,
  NihalbCastingObjectTypeB,
  NihalbCastingObjectTypeC,
  ObjectTypeWithAllPropertyTypes,
  OsdkTestObject,
  Person,
  RhemmingsObjectWithGtsrProperty2,
  SotSensor,
  StateTerritory,
  StructPerson,
  StructPersonOpisTeam,
  TestGeoAction,
  Todo,
  UnstructuredImageExample,
  Venture,
  WeatherStation,
} from './ontology/objects.js';
export * as $Objects from './ontology/objects.js';
export {
  getBusFromSet,
  getBusId,
  getBusInterface,
  getBusInterfaceSet,
  getFirstSecondElementOf2DArray,
  getNamesOfCustomersFromCountry,
  getTodoCount,
  identity2DArray,
  queryTakesAllParameterTypes,
} from './ontology/queries.js';
export * as $Queries from './ontology/queries.js';
export { $osdkMetadata } from './OntologyMetadata.js';
export { $ontologyRid } from './OntologyMetadata.js';
