#!/usr/bin/env node
/*
 * Copyright 2025 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable no-console */

/**
 * Generates component props reference tables in `docs/*.md` directly from the
 * TypeScript interface that declares each component's props, so the published
 * docs never drift from the source.
 *
 * This script is component-agnostic: each doc declares its own source via the
 * AUTOGEN:props START marker, so adding a new component needs no change here —
 * just add a marker block to its doc:
 *
 *   <!-- AUTOGEN:props START src=src/object-table/ObjectTableApi.ts interface=ObjectTableProps -->
 *   <!-- AUTOGEN:props END -->
 *
 * `src` is resolved relative to the package root. The script scans every
 * `docs/**\/*.md`, regenerates each marker block in place from the named
 * interface, then runs the doc through `oxfmt` so column alignment and
 * whitespace match repo style (and never fight the pre-commit `oxfmt` check).
 *
 * Usage:
 *   node scripts/gen-props.mjs           # write the tables
 *   node scripts/gen-props.mjs --check   # fail if any doc is out of date
 *
 * `--check` backs the `check-gen-props` task (part of `pnpm turbo check`),
 * which fails CI when a committed table has drifted from its source.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import ts from "typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.join(__dirname, "..");
const DOCS_DIR = path.join(PKG_ROOT, "docs");
// Repo-root oxfmt config (same one the package's `lint` task passes to oxfmt),
// resolved absolutely so the formatter agrees regardless of the caller's cwd.
const OXFMT_CONFIG = path.join(PKG_ROOT, "..", "..", "oxfmt.config.ts");
const GEN_CMD = "pnpm --filter @osdk/react-components gen-props";

const END_MARKER = "<!-- AUTOGEN:props END -->";

function startMarker(src, interfaceName) {
  return (
    `<!-- AUTOGEN:props START src=${src} interface=${interfaceName} ` +
    `— generated by scripts/gen-props.mjs; run \`${GEN_CMD}\` -->`
  );
}

/** Read a `key=value` attribute (value runs until whitespace) from a marker.
 * Anchored on whitespace (or start) so e.g. reading `src` doesn't match a
 * suffix inside a hypothetical `default-src=...`. */
export function getAttr(attrs, key) {
  const match = new RegExp(`(?:^|\\s)${key}=(\\S+)`, "u").exec(attrs);
  return match ? match[1] : undefined;
}

/** Stringify a JSDoc `{@link Entity.Name}` target. */
function entityNameToString(name) {
  if (name == null) return "";
  if (ts.isIdentifier(name)) return name.text;
  if (ts.isQualifiedName(name)) {
    return `${entityNameToString(name.left)}.${name.right.text}`;
  }
  return String(name.text ?? "");
}

/**
 * Render a JSDoc comment (a plain string, or a NodeArray of comment parts when
 * it contains `{@link}`) to markdown, turning each `{@link X}` into an inline
 * `` `X` `` code span. When the link has display text (`{@link X|label}` or
 * `{@link X label}`), the display text is used as the code-span label, since
 * that's what the author wrote for the reader. Otherwise the target name is
 * used.
 */
export function renderComment(comment) {
  if (comment == null) return "";
  if (typeof comment === "string") return comment;
  return comment
    .map((part) => {
      if (
        part.kind === ts.SyntaxKind.JSDocLink ||
        part.kind === ts.SyntaxKind.JSDocLinkCode ||
        part.kind === ts.SyntaxKind.JSDocLinkPlain
      ) {
        const name = entityNameToString(part.name);
        // TS preserves the `|` separator in `text` for pipe-form links
        // (e.g. `{@link Foo|bar}` -> text === "|bar"); strip it so the label
        // doesn't render with a stray pipe.
        const text = (part.text ?? "").replace(/^\|/u, "").trim();
        const label = text || name;
        return label ? `\`${label}\`` : "";
      }
      return part.text ?? "";
    })
    .join("");
}

/**
 * Flatten a multi-line JSDoc comment into a single line that fits in a
 * Markdown table cell (cells can't contain real line breaks). Used for the
 * description column — the main comment plus `@default` / `@deprecated` text.
 *
 * Newlines are treated by intent:
 * - A blank line is a deliberate paragraph break, so it's preserved as a
 *   visible `<br /><br />`.
 * - A single newline is just a soft wrap in the source, so it collapses to a
 *   space to keep the sentence flowing.
 *
 * Remaining whitespace runs collapse to one space, and the ends are trimmed.
 */
export function collapseProse(text) {
  return text
    .replaceAll("\r\n", "\n") // normalize line endings
    .replaceAll(/\n[ \t]*\n+/gu, "<br /><br />") // blank line(s) -> paragraph break
    .replaceAll("\n", " ") // soft wrap -> space
    .replaceAll(/[ \t]+/gu, " ") // collapse whitespace runs
    .trim();
}

/** Collapse all interior whitespace in a type string to single spaces, drop
 * the stray padding inside generic brackets and parens that multi-line types
 * leave behind (e.g. `Record< string, never >` -> `Record<string, never>`,
 * `( arg: T, ) => U` -> `(arg: T) => U`), and strip block comments that inline
 * object-type literals carry in their source text. */
export function collapseType(text) {
  return text
    .replaceAll(/\/\*[\s\S]*?\*\//gu, " ")
    .replaceAll(/\s+/gu, " ")
    .replaceAll(/<\s+/gu, "<")
    .replaceAll(/\s+>/gu, ">")
    .replaceAll(/\(\s+/gu, "(")
    .replaceAll(/,?\s+\)/gu, ")")
    .trim();
}

/** Escape `|` so it survives GFM table-cell parsing (even inside code spans). */
function escapeCell(text) {
  return text.replaceAll("|", "\\|");
}

function getTag(member, tagName) {
  return ts.getJSDocTags(member).find((tag) => tag.tagName.text === tagName);
}

function getMainComment(member) {
  for (const node of ts.getJSDocCommentsAndTags(member)) {
    if (ts.isJSDoc(node) && node.comment != null) {
      return renderComment(node.comment);
    }
  }
  return "";
}

function buildDescription(member, isRequired) {
  const parts = [];

  if (isRequired) parts.push("**Required.**");

  const deprecatedTag = getTag(member, "deprecated");
  if (deprecatedTag != null) {
    const msg = collapseProse(renderComment(deprecatedTag.comment));
    parts.push(msg ? `**Deprecated** — ${msg}` : "**Deprecated.**");
  }

  const mainComment = collapseProse(getMainComment(member));
  if (mainComment) parts.push(mainComment);

  const defaultTag = getTag(member, "default");
  if (defaultTag != null) {
    const value = collapseProse(renderComment(defaultTag.comment));
    if (value) {
      if (value.includes("`")) {
        // The default is prose with embedded code spans (can't be wrapped in
        // a single code span); render it inline as-is.
        const sep = /[.!?)]$/u.test(value) ? "" : ".";
        parts.push(`Defaults to ${value}${sep}`);
      } else {
        parts.push(`Defaults to \`${value}\`.`);
      }
    }
  }

  return escapeCell(parts.join(" "));
}

// ---------------------------------------------------------------------------
// Props-type resolver
//
// Resolves a named props type (interface OR type alias) to a flat, ordered,
// deduped list of property entries. Handles the shapes component props use in
// this package: interface `extends` clauses, intersections (`A & B`), unions
// (controlled/uncontrolled discriminated props), inline type literals, and
// `Pick<X, K>` / `Omit<X, K>`. Type references are resolved first among the
// current file's top-level declarations, then by following named imports into
// other files (so a base shared across files — e.g. `FilterDefinitionControls`
// — still contributes its members). External/bare imports are left unresolved.
//
// Each entry is `{ name, member, forcedOptional }`; `member` keeps its own
// source file (parent pointers are set), so `member.getText()` renders the
// right text even for members pulled in from another file. `forcedOptional` is
// set when a prop is optional in *some* union branch (or absent from one), so
// the controlled/uncontrolled split doesn't mislabel an optional prop.
// ---------------------------------------------------------------------------

/** Build (and cache) a name -> declaration map of a file's top-level
 * interfaces and type aliases. */
const declMapCache = new Map();
function declarationMap(sourceFile) {
  let byName = declMapCache.get(sourceFile);
  if (byName == null) {
    byName = new Map();
    sourceFile.forEachChild((node) => {
      if (
        (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) &&
        node.name != null
      ) {
        byName.set(node.name.text, node);
      }
    });
    declMapCache.set(sourceFile, byName);
  }
  return byName;
}

/** Find the module specifier a named import for `name` comes from, if any. */
function importSpecifierFor(name, sourceFile) {
  for (const stmt of sourceFile.statements) {
    if (!ts.isImportDeclaration(stmt)) continue;
    const named = stmt.importClause?.namedBindings;
    if (named == null || !ts.isNamedImports(named)) continue;
    for (const el of named.elements) {
      if (el.name.text === name) return stmt.moduleSpecifier.text;
    }
  }
  return undefined;
}

/** Resolve a relative import specifier to an on-disk `.ts`/`.tsx` file.
 * ESM imports carry `.js`, which maps back to the `.ts(x)` source. Bare
 * (non-relative) specifiers resolve to `undefined`. */
function resolveModulePath(spec, fromFile) {
  if (!spec.startsWith(".")) return undefined;
  const base = path.resolve(path.dirname(fromFile), spec);
  const candidates = [];
  if (base.endsWith(".js")) {
    candidates.push(`${base.slice(0, -3)}.ts`, `${base.slice(0, -3)}.tsx`);
  } else if (base.endsWith(".jsx")) {
    candidates.push(`${base.slice(0, -4)}.tsx`);
  }
  candidates.push(
    `${base}.ts`,
    `${base}.tsx`,
    path.join(base, "index.ts"),
    path.join(base, "index.tsx")
  );
  return candidates.find((c) => existsSync(c));
}

/** Resolve a type/interface name to `{ decl, sourceFile }`, looking in the
 * current file first, then following a named import into another file. */
function lookupName(name, sourceFile) {
  const local = declarationMap(sourceFile).get(name);
  if (local != null) return { decl: local, sourceFile };

  const spec = importSpecifierFor(name, sourceFile);
  if (spec != null) {
    const target = resolveModulePath(spec, sourceFile.fileName);
    if (target != null) {
      const imported = getSourceFile(target);
      const decl = declarationMap(imported).get(name);
      if (decl != null) return { decl, sourceFile: imported };
    }
  }
  return undefined;
}

/** Extract `{ name, args }` from a type reference or `extends` expression. */
function referenceInfo(node) {
  if (ts.isTypeReferenceNode(node)) {
    return {
      name: entityNameToString(node.typeName),
      args: node.typeArguments,
    };
  }
  if (
    ts.isExpressionWithTypeArguments(node) &&
    ts.isIdentifier(node.expression)
  ) {
    return { name: node.expression.text, args: node.typeArguments };
  }
  return undefined;
}

/** Collect the string keys named by a `Pick`/`Omit` key argument. */
function literalKeys(node) {
  const keys = new Set();
  const add = (n) => {
    if (ts.isLiteralTypeNode(n) && ts.isStringLiteral(n.literal)) {
      keys.add(n.literal.text);
    }
  };
  if (node == null) return keys;
  if (ts.isUnionTypeNode(node)) node.types.forEach(add);
  else add(node);
  return keys;
}

/** Concatenate entry lists into one, deduped by name. On a name collision the
 * later entry wins — so an interface's own member overrides the base it
 * `extends` (matching TypeScript, where the derived declaration takes
 * precedence) — while keeping the name's first-seen position in the table. */
function dedupe(lists) {
  const out = [];
  const indexByName = new Map();
  for (const list of lists) {
    for (const entry of list) {
      const at = indexByName.get(entry.name);
      if (at == null) {
        indexByName.set(entry.name, out.length);
        out.push(entry);
      } else {
        out[at] = entry;
      }
    }
  }
  return out;
}

/** Merge union branches: a prop is optional if optional in or absent from any. */
function mergeUnion(branches) {
  const present = branches.map((list) => new Set(list.map((e) => e.name)));
  const byName = new Map();
  const order = [];
  for (const list of branches) {
    for (const entry of list) {
      let agg = byName.get(entry.name);
      if (agg == null) {
        agg = { ...entry };
        byName.set(entry.name, agg);
        order.push(agg);
      }
      if (entry.forcedOptional) agg.forcedOptional = true;
    }
  }
  for (const agg of order) {
    if (!present.every((set) => set.has(agg.name))) agg.forcedOptional = true;
  }
  return order;
}

/** A documentable member: a property or method signature carrying a type. */
function isDocumentableMember(member) {
  return (
    (ts.isPropertySignature(member) || ts.isMethodSignature(member)) &&
    member.type != null
  );
}

/** Render a member's type for the Type column. Property signatures use their
 * declared type; a method signature (`foo(arg): T`) is rendered as the
 * equivalent function type `(arg) => T` so it reads like the other callbacks
 * (and so its parameters aren't dropped, leaving only the return type). */
function memberTypeText(member) {
  if (ts.isMethodSignature(member)) {
    const params = member.parameters.map((p) => p.getText()).join(", ");
    return `(${params}) => ${member.type.getText()}`;
  }
  return member.type.getText();
}

function propertyEntry(member) {
  return {
    name: member.name.getText(),
    member,
    forcedOptional: member.questionToken != null,
  };
}

function membersOfDeclaration(decl, sourceFile, seen) {
  if (ts.isTypeAliasDeclaration(decl)) {
    return membersOfType(decl.type, sourceFile, seen);
  }
  // InterfaceDeclaration: inherited (`extends`) members first, then own.
  const inherited = [];
  for (const clause of decl.heritageClauses ?? []) {
    if (clause.token === ts.SyntaxKind.ExtendsKeyword) {
      for (const type of clause.types) {
        inherited.push(membersOfType(type, sourceFile, seen));
      }
    }
  }
  const own = decl.members.filter(isDocumentableMember).map(propertyEntry);
  return dedupe([...inherited, own]);
}

function membersOfType(typeNode, sourceFile, seen) {
  if (ts.isParenthesizedTypeNode(typeNode)) {
    return membersOfType(typeNode.type, sourceFile, seen);
  }
  if (ts.isTypeLiteralNode(typeNode)) {
    return typeNode.members.filter(isDocumentableMember).map(propertyEntry);
  }
  if (ts.isIntersectionTypeNode(typeNode)) {
    return dedupe(
      typeNode.types.map((t) => membersOfType(t, sourceFile, seen))
    );
  }
  if (ts.isUnionTypeNode(typeNode)) {
    return mergeUnion(
      typeNode.types.map((t) => membersOfType(t, sourceFile, seen))
    );
  }

  const ref = referenceInfo(typeNode);
  if (ref != null) {
    if (
      (ref.name === "Pick" || ref.name === "Omit") &&
      ref.args?.length === 2
    ) {
      const base = membersOfType(ref.args[0], sourceFile, seen);
      const keys = literalKeys(ref.args[1]);
      return ref.name === "Pick"
        ? base.filter((e) => keys.has(e.name))
        : base.filter((e) => !keys.has(e.name));
    }
    const found = lookupName(ref.name, sourceFile);
    if (found != null) {
      // Key the recursion guard by file + name (names can collide across files).
      const key = `${found.sourceFile.fileName}#${ref.name}`;
      if (seen.has(key)) return []; // already resolving this type up the stack
      seen.add(key);
      const result = membersOfDeclaration(found.decl, found.sourceFile, seen);
      seen.delete(key);
      return result;
    }
    // A named type we were asked to pull members from but couldn't resolve
    // (external/bare import, re-export, or aliased import).
    console.error(
      `gen-props: could not resolve \`${ref.name}\` — any props it ` +
        `contributes will be missing from the generated table.`
    );
  }
  // Unsupported constructs contribute no members.
  return [];
}

/** Render a type parameter with its constraint and default, e.g.
 * `Q extends ActionDefinition<unknown>` or
 * `RDPs extends Record<string, SimplePropertyDef> = Record<string, never>`. */
function renderTypeParam(tp) {
  let text = tp.name.getText();
  if (tp.constraint != null) text += ` extends ${tp.constraint.getText()}`;
  if (tp.default != null) text += ` = ${tp.default.getText()}`;
  return escapeCell(collapseType(text));
}

export function resolveProps(sourceFile, typeName) {
  const found = lookupName(typeName, sourceFile);
  if (found == null) return undefined;
  const seen = new Set([`${found.sourceFile.fileName}#${typeName}`]);
  return {
    entries: membersOfDeclaration(found.decl, found.sourceFile, seen),
    typeParams: (found.decl.typeParameters ?? []).map(renderTypeParam),
  };
}

export function buildRows(entries) {
  const rows = [];
  for (const { name, member, forcedOptional } of entries) {
    const type = escapeCell(collapseType(memberTypeText(member)));
    const isRequired = member.questionToken == null && !forcedOptional;
    const description = buildDescription(member, isRequired);
    rows.push(`| \`${name}\` | \`${type}\` | ${description} |`);
  }
  return rows;
}

function buildBlock(rows, typeParams, src, interfaceName) {
  // Surface the props type's generic parameters (and their constraints) so
  // bare `Q`-style types in the table are meaningful.
  const typeParamLine =
    typeParams.length > 0
      ? [
          "Type parameters: " + typeParams.map((tp) => `\`${tp}\``).join(", "),
          "",
        ]
      : [];
  return [
    startMarker(src, interfaceName),
    "",
    ...typeParamLine,
    "| Name | Type | Description |",
    "| ---- | ---- | ----------- |",
    ...rows,
    "",
    END_MARKER,
  ].join("\n");
}

const sourceCache = new Map();
export function getSourceFile(absPath) {
  let sourceFile = sourceCache.get(absPath);
  if (sourceFile == null) {
    const text = readFileSync(absPath, "utf-8");
    const scriptKind = absPath.endsWith(".tsx")
      ? ts.ScriptKind.TSX
      : ts.ScriptKind.TS;
    sourceFile = ts.createSourceFile(
      absPath,
      text,
      ts.ScriptTarget.Latest,
      /* setParentNodes */ true,
      scriptKind
    );
    sourceCache.set(absPath, sourceFile);
  }
  return sourceFile;
}

/** Recursively collect every `.md` file under `dir`. */
function findMarkdownFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...findMarkdownFiles(full));
    } else if (entry.name.endsWith(".md")) {
      out.push(full);
    }
  }
  return out;
}

/** Canonical form of an AUTOGEN block for change detection: drop the
 * column-alignment whitespace and separator dash-runs that `oxfmt` owns, so a
 * freshly built (unaligned) block compares equal to its committed, oxfmt-
 * aligned form when the underlying props are unchanged. Cell *content* never
 * varies by whitespace alone (descriptions/types are pre-collapsed), so this
 * can't mask a real diff. */
export function tableSignature(block) {
  return block.replaceAll(/[ \t]+/gu, "").replaceAll(/-+/gu, "-");
}

/** Run a doc through `oxfmt` so its table alignment, surrounding whitespace, and
 * embedded code fences match the repo style the pre-commit hook enforces.
 * `--stdin-filepath` makes oxfmt pick the markdown parser from the doc's name
 * while reading the block-replaced content from stdin. */
function oxfmtFormat(input, docPath) {
  return execFileSync(
    "npx",
    ["oxfmt", "-c", OXFMT_CONFIG, "--stdin-filepath", docPath],
    {
      input,
      encoding: "utf-8",
    }
  );
}

/**
 * Regenerate every AUTOGEN:props block in `docPath` and return the formatted
 * doc, or `null` if the doc has no markers. `format` is injectable so tests can
 * observe whether the (expensive) `oxfmt` step ran without spawning it.
 */
export function renderDoc(docPath, format = oxfmtFormat) {
  const original = readFileSync(docPath, "utf-8");
  if (!original.includes("<!-- AUTOGEN:props START")) return null;

  // Local regex instance — keeps `lastIndex` state from leaking between calls
  // if anyone later switches from `replace` to `exec`/`test`.
  const blockRe =
    /<!-- AUTOGEN:props START\b([^>]*?)-->[\s\S]*?<!-- AUTOGEN:props END -->/gu;
  const rel = path.relative(PKG_ROOT, docPath);
  let blockChanged = false;
  const replaced = original.replace(blockRe, (_match, attrs) => {
    const src = getAttr(attrs, "src");
    const interfaceName = getAttr(attrs, "interface");
    if (src == null || interfaceName == null) {
      throw new Error(
        `AUTOGEN:props marker in ${rel} must declare both ` +
          `\`src=<path>\` and \`interface=<name>\`.`
      );
    }
    const absSrc = path.join(PKG_ROOT, src);
    const sourceFile = getSourceFile(absSrc);
    const resolved = resolveProps(sourceFile, interfaceName);
    if (resolved == null) {
      throw new Error(
        `Could not find interface or type ${interfaceName} in ${src}`
      );
    }
    if (resolved.entries.length === 0) {
      throw new Error(
        `${interfaceName} in ${src} resolved to no documentable props.`
      );
    }
    const block = buildBlock(
      buildRows(resolved.entries),
      resolved.typeParams,
      src,
      interfaceName
    );
    if (tableSignature(block) !== tableSignature(_match)) {
      blockChanged = true;
    }
    return block;
  });

  // Fast path: regeneration touched no block (ignoring the alignment
  // whitespace `oxfmt` owns), so the committed doc — already oxfmt-formatted
  // by the pre-commit hook — is up to date. Skip the per-doc `oxfmt`
  // subprocess, which otherwise dominates this script's runtime.
  if (!blockChanged) return { rel, original, formatted: original };

  return { rel, original, formatted: format(replaced, docPath) };
}

function main() {
  const check = process.argv.includes("--check");

  const docs = findMarkdownFiles(DOCS_DIR)
    .map((docPath) => ({ docPath, result: renderDoc(docPath) }))
    .filter(({ result }) => result != null);

  if (docs.length === 0) {
    console.log("No docs with AUTOGEN:props markers found.");
    return;
  }

  if (check) {
    const stale = docs.filter(
      ({ result }) => result.formatted !== result.original
    );
    if (stale.length > 0) {
      console.error(
        `❌ ${stale.length} doc(s) out of date:\n` +
          stale.map(({ result }) => `   - ${result.rel}`).join("\n") +
          `\n   Run \`${GEN_CMD}\` and commit the result.`
      );
      process.exit(1);
    }
    console.log(`✅ ${docs.length} props table(s) up to date`);
    return;
  }

  let written = 0;
  for (const { docPath, result } of docs) {
    if (result.formatted !== result.original) {
      writeFileSync(docPath, result.formatted, "utf-8");
      written++;
      console.log(`✨ Wrote ${result.rel}`);
    }
  }
  console.log(
    written === 0
      ? `✅ ${docs.length} props table(s) already up to date`
      : `✨ Updated ${written} of ${docs.length} doc(s)`
  );
}

// Only run when invoked as a script (`node scripts/gen-props.mjs`); stay inert
// when imported (e.g. by the unit tests) so the exported helpers can be
// exercised in isolation.
if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
