/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Action parameter and return-shape helpers. The full
// `client(MyAction).applyAction(args, options)` signature is composed in
// @osdk/client; from @osdk/api we pin the per-shape param helpers
// (`ActionParam.ObjectType` etc.), the options bag, and the two non-trivial
// return branches (edits-bearing and validation-only).

import type {
  ActionEditResponse,
  ActionParam,
  ActionValidationResponse,
  ApplyActionOptions,
  ApplyBatchActionOptions,
} from "../../actions/Actions.js";
import type { EmployeeApiTest } from "../../test/EmployeeApiTest.js";
import type { FooInterfaceApiTest } from "../../test/FooInterfaceApiTest.js";

// === Param shapes (what an action accepts for each parameter type) ===

/** What an object-typed action parameter accepts — primary key or full object identifiers. */
declare const actionParam_objectType: ActionParam.ObjectType<EmployeeApiTest>;

/** What an objectSet-typed action parameter accepts. */
declare const actionParam_objectSetType: ActionParam.ObjectSetType<EmployeeApiTest>;

/** What an interface-typed action parameter accepts. */
declare const actionParam_interfaceType: ActionParam.InterfaceType<FooInterfaceApiTest>;

/** A primitive (string) action parameter. */
declare const actionParam_primitiveType_string: ActionParam.PrimitiveType<"string">;

/** A primitive (attachment) action parameter — non-trivial wire mapping. */
declare const actionParam_primitiveType_attachment: ActionParam.PrimitiveType<"attachment">;

/** A struct-typed action parameter — fields are mapped through DataValueClientToWire. */
declare const actionParam_structType: ActionParam.StructType<{
  name: "string";
  age: "integer";
  joined: "datetime";
}>;

/** The marker type for clearing a nullable parameter on an autogenerated modify action. */
declare const actionParam_nullValueType: ActionParam.NullValueType;

// === Options bag ===

/** The options accepted by client(action).applyAction(args, options). */
declare const applyActionOptions: ApplyActionOptions;

/** The options accepted by client(action).batchApplyAction(args, options). */
declare const applyBatchActionOptions: ApplyBatchActionOptions;

// === Return shapes ===

/** The edits-bearing payload returned when $returnEdits: true. */
declare const actionEditResponse: ActionEditResponse;

/** The validation-only response returned when $validateOnly: true. */
declare const actionValidationResponse: ActionValidationResponse;
