/*
 * Copyright 2025 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Placeholder. scripts/build-css.mjs OVERWRITES the transpiled
// build/esm/styles.js with a runtime-injection module that adds devtools
// styles (including Blueprint) to document.head when the package is
// imported. The throw below guarantees that a published bundle missing the
// build-css step fails loudly instead of silently shipping unstyled UI.
//
// Tests / dev never hit this file at runtime: vitest reads the source tree
// directly via vite's sass + CSS-modules pipeline (VITEST env is set), and
// IDE typechecks never execute it.

if (typeof process === "undefined" || process.env?.VITEST !== "true") {
  throw new Error(
    "@osdk/react-devtools: build is incomplete — build/esm/styles.js was "
      + "not regenerated by scripts/build-css.mjs. Run `pnpm transpileEsm` "
      + "to produce a publishable bundle.",
  );
}

export {};
