/*
 * Copyright 2026 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

const TOKENS_DIR = join(
  __dirname,
  "../../../../..",
  "react-components/src/tokens",
);

const OUTPUT_FILE = join(__dirname, "..", "generated-token-inventory.ts");

/** Files to skip: dark overrides and Blueprint palette primitives */
const SKIP_FILES = new Set(["dark.css", "blueprint-design-tokens.css"]);

const TOKEN_DIRS = ["base-tokens", "component-tokens"];

/**
 * Extract all `--osdk-*` property declarations from :root blocks in a CSS file.
 * Matches lines like: `--osdk-foo-bar: <value>;`
 */
function extractTokensFromCss(cssContent) {
  const tokens = [];
  // Match --osdk-* property declarations (property: value pairs inside :root)
  const propRegex = /^\s*(--osdk-[\w-]+)\s*:\s*(.+?)\s*;/gm;
  let match;
  while ((match = propRegex.exec(cssContent)) != null) {
    tokens.push({
      variable: match[1],
      defaultValue: match[2].trim(),
    });
  }
  return tokens;
}

/** Derive a category name from the CSS filename (e.g. "input.css" -> "input") */
function categoryFromFilename(filename) {
  return basename(filename, ".css");
}

function main() {
  /** @type {Map<string, {variable: string, defaultValue: string, sourceFile: string, category: string}>} */
  const seen = new Map();

  for (const dir of TOKEN_DIRS) {
    const dirPath = join(TOKENS_DIR, dir);
    let files;
    try {
      files = readdirSync(dirPath).filter((f) => f.endsWith(".css")).sort();
    } catch {
      process.stderr.write(`Warning: could not read ${dirPath}\n`);
      continue;
    }

    for (const file of files) {
      if (SKIP_FILES.has(file)) continue;

      const filePath = join(dirPath, file);
      const content = readFileSync(filePath, "utf-8");
      const tokens = extractTokensFromCss(content);
      const sourceFile = relative(
        join(TOKENS_DIR, ".."),
        filePath,
      ).replaceAll("\\", "/");
      const category = categoryFromFilename(file);

      for (const token of tokens) {
        // First declaration wins (base before component)
        if (!seen.has(token.variable)) {
          seen.set(token.variable, {
            variable: token.variable,
            defaultValue: token.defaultValue,
            sourceFile,
            category,
          });
        }
      }
    }
  }

  const entries = [...seen.values()].sort((a, b) =>
    a.variable.localeCompare(b.variable)
  );

  const lines = [
    "/*",
    " * AUTO-GENERATED by extract-tokens.mjs — do not edit manually.",
    ` * Generated: ${new Date().toISOString().split("T")[0]}`,
    ` * Token count: ${entries.length}`,
    " */",
    "",
    "import type { TokenInventoryEntry } from \"./types.js\";",
    "",
    "export const TOKEN_INVENTORY: TokenInventoryEntry[] = [",
  ];

  for (const entry of entries) {
    const escaped = entry.defaultValue.replaceAll("\\", "\\\\").replaceAll(
      "\"",
      "\\\"",
    );
    lines.push(
      `  { variable: "${entry.variable}", defaultValue: "${escaped}", sourceFile: "${entry.sourceFile}", category: "${entry.category}" },`,
    );
  }

  lines.push("];", "");

  writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");
  process.stdout.write(
    `Wrote ${entries.length} tokens to ${
      relative(process.cwd(), OUTPUT_FILE)
    }\n`,
  );
}

main();
