name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 21]

    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2
        with:
          version: 8.7.4

      - name: Setup Node.js environment
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build, lint, and test
        run: pnpm check

      - name: Verify nothing changed
        run: git diff --exit-code

      - name: Verify nothing added
        run: u="$(git ls-files --others --exclude-standard)" && test -z "$u"