/*
 * Copyright 2025 Palantir Technologies, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { kebab } from "../defineAction.js";
import type {
  ActionParameterV2Config,
  ActionPrimitiveType,
  ActionV2Config,
  ActionV2Def,
} from "./defineActionV2.js";
import { defineActionV2 } from "./defineActionV2.js";
import type { ObjectV2Config, ObjectV2Def } from "./defineObjectV2.js";
import type { PropertyV2Config } from "./propertyMapping.js";

// ---------------------------------------------------------------------------
// Overrides interfaces
// ---------------------------------------------------------------------------

/**
 * Optional overrides for auto-generated object action definitions.
 */
export interface ActionV2Overrides {
  apiName?: string;
  displayName?: string;
  status?: "active" | "experimental" | "example";
  excludedProperties?: string[];
}

/**
 * Overrides for create-or-modify actions, with an additional primaryKeyOption.
 */
export interface CreateOrModifyV2Overrides extends ActionV2Overrides {
  primaryKeyOption?: "autoGenerated" | "userInput";
}

// ---------------------------------------------------------------------------
// Runtime helpers
// ---------------------------------------------------------------------------

/** Check whether a PropertyV2Config describes a struct-typed property. */
function isStructProperty(prop: PropertyV2Config): boolean {
  if (typeof prop === "string") return false;
  const t = prop.type;
  return typeof t === "object" && t.type === "struct";
}

/**
 * Extract the action primitive type string from a PropertyV2Config.
 * Maps "date" to "datetime" (action parameters use "datetime", not "date").
 */
function propertyToActionType(
  prop: PropertyV2Config,
): string {
  const raw = typeof prop === "string" ? prop : (
    typeof prop.type === "string" ? prop.type : prop.type.type
  );
  if (raw === "date") return "datetime";
  return raw;
}

/**
 * Build the action parameter record from an ObjectV2Def's properties.
 *
 * - Always excludes struct properties.
 * - Optionally excludes the primary key.
 * - Optionally marks all params as nullable.
 * - Respects excludedProperties from overrides.
 */
function buildPropertyParams(
  objectDef: ObjectV2Def,
  opts: {
    excludePk: boolean;
    nullable: boolean;
    excludedProperties?: string[];
  },
): Record<string, ActionParameterV2Config> {
  const params: Record<string, ActionParameterV2Config> = {};
  const excluded = new Set(opts.excludedProperties ?? []);

  for (const [key, prop] of Object.entries(objectDef.properties)) {
    if (isStructProperty(prop)) continue;
    if (opts.excludePk && key === objectDef.primaryKeyPropertyApiName) continue;
    if (excluded.has(key)) continue;

    const actionType = propertyToActionType(prop);
    if (opts.nullable) {
      params[key] = {
        type: actionType,
        nullable: true,
      } as ActionParameterV2Config;
    } else {
      params[key] = actionType as ActionParameterV2Config;
    }
  }

  return params;
}

// ---------------------------------------------------------------------------
// Type-level helpers
// ---------------------------------------------------------------------------

/**
 * Map a PropertyV2Config to the corresponding action parameter type.
 * Returns ActionPrimitiveType to satisfy ActionParameterV2Config constraints.
 * Maps "date" -> "datetime" since actions use "datetime".
 */
type PropertyToActionPrimitive<P> = P extends "date" ? "datetime"
  : P extends ActionPrimitiveType ? P
  : P extends string ? ActionPrimitiveType
  : P extends { type: { type: "struct" } } ? never
  : P extends { type: "date" } ? "datetime"
  : P extends { type: infer T extends ActionPrimitiveType } ? T
  : P extends { type: infer _T extends string } ? ActionPrimitiveType
  : ActionPrimitiveType;

/** Extract keys from a properties record that are NOT struct-typed. */
type NonStructKeys<Props> =
  & {
    [K in keyof Props]: Props[K] extends { type: { type: "struct" } } ? never
      : K;
  }[keyof Props]
  & string;

// -- Create --

type CreateActionConfig<T extends ObjectV2Config> = {
  apiName: `create-object-${string}`;
  displayName: `Create ${T["displayName"]}`;
  parameters: {
    [K in NonStructKeys<T["properties"]>]: PropertyToActionPrimitive<
      T["properties"][K]
    >;
  };
  modifiedEntities: {
    [K in T["apiName"]]: { created: true; modified: false };
  };
};

// -- Modify --

type ModifyActionConfig<T extends ObjectV2Config> = {
  apiName: `modify-object-${string}`;
  displayName: `Modify ${T["displayName"]}`;
  parameters:
    & {
      objectToModifyParameter: {
        type: "object";
        objectType: ObjectV2Def<T>;
        nullable: false;
      };
    }
    & {
      [
        K in
          & NonStructKeys<T["properties"]>
          & Exclude<keyof T["properties"], T["primaryKeyPropertyApiName"]>
      ]: {
        type: PropertyToActionPrimitive<T["properties"][K]>;
        nullable: true;
      };
    };
  modifiedEntities: {
    [K in T["apiName"]]: { created: false; modified: true };
  };
};

// -- Delete --

type DeleteActionConfig<T extends ObjectV2Config> = {
  apiName: `delete-object-${string}`;
  displayName: `Delete ${T["displayName"]}`;
  parameters: {
    objectToDeleteParameter: {
      type: "object";
      objectType: ObjectV2Def<T>;
      nullable: false;
    };
  };
  modifiedEntities: {
    [K in T["apiName"]]: { created: false; modified: false; deleted: true };
  };
};

// -- CreateOrModify --

type CreateOrModifyActionConfig<T extends ObjectV2Config> = {
  apiName: `create-or-modify-${string}`;
  displayName: `Create or Modify ${T["displayName"]}`;
  parameters:
    & {
      objectToCreateOrModifyParameter: {
        type: "object";
        objectType: ObjectV2Def<T>;
        nullable: false;
      };
    }
    & {
      [
        K in
          & NonStructKeys<T["properties"]>
          & Exclude<keyof T["properties"], T["primaryKeyPropertyApiName"]>
      ]: {
        type: PropertyToActionPrimitive<T["properties"][K]>;
        nullable: true;
      };
    };
  modifiedEntities: {
    [K in T["apiName"]]: { created: true; modified: true };
  };
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Define a "create object" action from an ObjectV2Def.
 *
 * Generates parameters for all non-struct properties (required) and an
 * addObjectRule targeting the object type.
 */
export function defineCreateObjectActionV2<
  const T extends ObjectV2Config,
>(
  objectDef: ObjectV2Def<T>,
  overrides?: ActionV2Overrides,
): ActionV2Def<CreateActionConfig<T>> {
  const apiName = overrides?.apiName
    ?? `create-object-${kebab(objectDef.apiName)}`;
  const displayName = overrides?.displayName
    ?? `Create ${objectDef.displayName}`;

  const parameters = buildPropertyParams(objectDef, {
    excludePk: false,
    nullable: false,
    excludedProperties: overrides?.excludedProperties,
  });

  const config: ActionV2Config = {
    apiName,
    displayName,
    parameters,
    modifiedEntities: {
      [objectDef.apiName]: { created: true, modified: false },
    },
  };

  return defineActionV2(config) as ActionV2Def<CreateActionConfig<T>>;
}

/**
 * Define a "modify object" action from an ObjectV2Def.
 *
 * Generates an objectToModifyParameter (object reference) plus parameters
 * for all non-struct, non-PK properties (nullable) and a modifyObjectRule.
 */
export function defineModifyObjectActionV2<
  const T extends ObjectV2Config,
>(
  objectDef: ObjectV2Def<T>,
  overrides?: ActionV2Overrides,
): ActionV2Def<ModifyActionConfig<T>> {
  const apiName = overrides?.apiName
    ?? `modify-object-${kebab(objectDef.apiName)}`;
  const displayName = overrides?.displayName
    ?? `Modify ${objectDef.displayName}`;

  const propertyParams = buildPropertyParams(objectDef, {
    excludePk: true,
    nullable: true,
    excludedProperties: overrides?.excludedProperties,
  });

  const parameters: Record<string, ActionParameterV2Config> = {
    objectToModifyParameter: {
      type: "object",
      objectType: objectDef,
      nullable: false,
    },
    ...propertyParams,
  };

  const config: ActionV2Config = {
    apiName,
    displayName,
    parameters,
    modifiedEntities: {
      [objectDef.apiName]: { created: false, modified: true },
    },
  };

  return defineActionV2(config) as ActionV2Def<ModifyActionConfig<T>>;
}

/**
 * Define a "delete object" action from an ObjectV2Def.
 *
 * Generates only an objectToDeleteParameter and a deleteObjectRule.
 */
export function defineDeleteObjectActionV2<
  const T extends ObjectV2Config,
>(
  objectDef: ObjectV2Def<T>,
  overrides?: ActionV2Overrides,
): ActionV2Def<DeleteActionConfig<T>> {
  const apiName = overrides?.apiName
    ?? `delete-object-${kebab(objectDef.apiName)}`;
  const displayName = overrides?.displayName
    ?? `Delete ${objectDef.displayName}`;

  const parameters: Record<string, ActionParameterV2Config> = {
    objectToDeleteParameter: {
      type: "object",
      objectType: objectDef,
      nullable: false,
    },
  };

  const config: ActionV2Config = {
    apiName,
    displayName,
    parameters,
    modifiedEntities: {
      [objectDef.apiName]: { created: false, modified: false, deleted: true },
    },
  };

  return defineActionV2(config) as ActionV2Def<DeleteActionConfig<T>>;
}

/**
 * Define a "create or modify object" action from an ObjectV2Def.
 *
 * Generates an objectToCreateOrModifyParameter (object reference) plus
 * parameters for all non-struct, non-PK properties (nullable) and an
 * addOrModifyObjectRuleV2.
 */
export function defineCreateOrModifyObjectActionV2<
  const T extends ObjectV2Config,
>(
  objectDef: ObjectV2Def<T>,
  overrides?: CreateOrModifyV2Overrides,
): ActionV2Def<CreateOrModifyActionConfig<T>> {
  const apiName = overrides?.apiName
    ?? `create-or-modify-${kebab(objectDef.apiName)}`;
  const displayName = overrides?.displayName
    ?? `Create or Modify ${objectDef.displayName}`;

  const propertyParams = buildPropertyParams(objectDef, {
    excludePk: true,
    nullable: true,
    excludedProperties: overrides?.excludedProperties,
  });

  const parameters: Record<string, ActionParameterV2Config> = {
    objectToCreateOrModifyParameter: {
      type: "object",
      objectType: objectDef,
      nullable: false,
    },
    ...propertyParams,
  };

  const config: ActionV2Config = {
    apiName,
    displayName,
    parameters,
    modifiedEntities: {
      [objectDef.apiName]: { created: true, modified: true },
    },
  };

  return defineActionV2(config) as ActionV2Def<CreateOrModifyActionConfig<T>>;
}
